src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleSettings.cs
src/Prowlarr.Api.V1/swagger.json

NO
"Freeleech" is misspelled in a couple places.
N/A

Fixed: Correct spelling of 'freeleech'

---

src/NzbDrone.Core/Applications/ApplicationBase.cs
src/NzbDrone.Core/Applications/ApplicationService.cs
src/NzbDrone.Core/Applications/IApplication.cs
src/NzbDrone.Core/Applications/Lidarr/Lidarr.cs
src/NzbDrone.Core/Applications/Lidarr/LidarrV1Proxy.cs
src/NzbDrone.Core/Applications/Radarr/Radarr.cs
src/NzbDrone.Core/Applications/Radarr/RadarrV3Proxy.cs
src/NzbDrone.Core/Applications/Readarr/Readarr.cs
src/NzbDrone.Core/Applications/Readarr/ReadarrV1Proxy.cs
src/NzbDrone.Core/Applications/Sonarr/Sonarr.cs
src/NzbDrone.Core/Applications/Sonarr/SonarrV3Proxy.cs

NO
During sync look for Indexers that exist on remote applications that point back to this Prowlarr instance and setup a map for them. Handle these cases where indexers are manually setup and then Sync is later turned on, or when mapping table was wiped but indexers remain in remote applications (cleanup) to avoid Prowlarr trying to setup a duplicate of the indexer.

New: Detect and map App Indexers setup outside of Prowlarr

---

frontend/src/Indexer/Info/IndexerInfoModalContent.js
src/NzbDrone.Core/Applications/ApplicationBase.cs
src/NzbDrone.Core/Applications/Lidarr/Lidarr.cs
src/NzbDrone.Core/Applications/Radarr/Radarr.cs
src/NzbDrone.Core/Applications/Readarr/Readarr.cs
src/NzbDrone.Core/Applications/Sonarr/Sonarr.cs
src/NzbDrone.Core/Indexers/DownloadMappingService.cs
src/Prowlarr.Api.V1/Indexers/IndexerController.cs
src/Prowlarr.Api.V1/Indexers/NewznabController.cs

NO
This will be a breaking change for existing users.  Not sure how the migration would work.
Moves the newznab endpoint to `/{id}/api`, eg `localhost:9696/1/api?t=caps`
* #

New: Move newznab endpoint to /{id}/api

---

src/NzbDrone.Core/Applications/ApplicationService.cs

NO
When an indexer is removed but the applications are down this will remove that application at the next "Application Indexer Sync"

New: Removal of indexers on application sync that are no longer defined within Prowlarr

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Definitions/Torznab/Torznab.cs

NO
Untested; theory should work
Ref
https://animetosho.org/about
Newznab/Torznab links to: `https://feed.animetosho.org/api`
>Is there a feed available?
>RSS2 (torrents only), Newznab/Torznab and ATOM. If you are trying to add any of these to an application which insists on an API key, please just put 0 as the key (or anything else, as Anime Tosho doesn't require an API key, but it's helpful if everyone uses the same key for server caching).
Is there an API available?
>The feed (see above) can serve as an API. You can also replace the rss2 or atom in the feed URL with json to get a JSON formatted version. The JSON API also supports querying torrent/file info if given a supplied torrent ID (example).
>Alternatively, daily database exports are also available for download here.
- Tests-N/A
- …

Add animetosho

---

src/Prowlarr.Http/Extensions/RequestExtensions.cs

NO
Grab port from request and not the connection to ensure we don't use it when not needed
* Fixes #71

Fixed: Port set for downloads even when not used Request

---

src/Prowlarr.Http/Extensions/RequestExtensions.cs

NO
Host based stats fall back to IP address when DNS resolution is not possible.

Fixed: Falls back to IP address when DNS resolution is not possible

---

src/Prowlarr.Http/Extensions/RequestExtensions.cs

NO
Fixes error when the request header is null and so doesn't have a Remote IP to parse. 
* Fixes #96

Fixed: Error when trying to parse the value 'Unknown' as an IP Address

---

src/NzbDrone.Common/Http/HttpResponse.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornParser.cs

NO
If location header is returned with relative path like `login.php`, Cardigann will fail with UriFormatException. This ensures we use the full redirect Uri instead of just the the location header value itself when location is relative.
* Fixes HD-Forever and others

Fixed: Cardigann redirect handling fails for relative location headers

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
Fixed: Cleanse Username prefixed with ': ' from logs
- remove unused var in log cleansing code
- 
- N/A Translation Keys
- N/A Wiki Updates
* #122 Logs

Fixed: Cleanse Username prefixed with ': ' from logs

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/AnimeWorld.cs

NO
Added support for the Unit3d API for the tracker AnimeWorld.
Before it used the Jackett definition, which was disliked by the admins.
Tested all the categories, they all returned the correct results

(Indexers) Add Support for Unit3d API / Convert AnimeWorld

---

frontend/src/System/Updates/UpdateChanges.js

NO
Currently, the regex to replace issues `#0000` only works on issues that are 4 or 5 characters, currently, as we are so early in the process, we are still going through 3 digits (156 being the highest at the time of writing) therefore they aren't replaced with links.
Fixes 
* Fixes #156

Adds a fix to support 3 digit issues

---

frontend/src/Indexer/Index/Table/IndexerIndexRow.js

NO
Removes `api.` from the beginning of the site links within the indexers table - this is based on the sites that I have access to and what was showing for those - others may be different and still need to be handled appropriately
* Fixes #183

Fixed: Website Links going to api not site

---

src/NzbDrone.Core/Datastore/Converters/CookieConverter.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/ThingiProvider/ProviderRepository.cs

NO
The current way of storing Cookies persistently is broken because the Cookies IDictionary<string, string> has a CamelCase Key Police. This results in the cookie key being converted to Camel Case which kills the cookie for some sites (like AnimeTorrents)
Fixes #217

fix(TableMapping): make own non Camel Case Converter for Cookies

---

src/NzbDrone.Core/Applications/Lidarr/Lidarr.cs
src/NzbDrone.Core/Applications/Lidarr/LidarrSettings.cs
src/NzbDrone.Core/Applications/Lidarr/LidarrV1Proxy.cs
src/NzbDrone.Core/Applications/Radarr/Radarr.cs
src/NzbDrone.Core/Applications/Radarr/RadarrSettings.cs
src/NzbDrone.Core/Applications/Radarr/RadarrV3Proxy.cs
src/NzbDrone.Core/Applications/Readarr/Readarr.cs
src/NzbDrone.Core/Applications/Readarr/ReadarrSettings.cs
src/NzbDrone.Core/Applications/Readarr/ReadarrV1Proxy.cs
src/NzbDrone.Core/Applications/Sonarr/Sonarr.cs
src/NzbDrone.Core/Applications/Sonarr/SonarrSettings.cs
src/NzbDrone.Core/Applications/Sonarr/SonarrV3Proxy.cs
src/Prowlarr.Api.V1/Indexers/NewznabController.cs

NO
Instead of just calling `System/Status` on the application to test connection, this extends the tests to do a mock indexer test call. This ensures the application calls back to Prowlarr to test the indexer connection thus testing both the connection to the app and the connection back to Prowlarr. This should eliminate or minimize the reports sync failing due to bad application settings.
This also adds code to the Newznab endpoint to return mock results if calling with indexer id of 0
* Fixes #209

New: Better Application Tests

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs
src/NzbDrone.Core/Indexers/Definitions/AnimeTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/Anthelion.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazSettings.cs
src/NzbDrone.Core/Indexers/Definitions/BakaBT.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListSettings.cs
src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleSettings.cs
src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBitsSettings.cs
src/NzbDrone.Core/Indexers/Definitions/HDTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/Headphones/HeadphonesSettings.cs
src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs
src/NzbDrone.Core/Indexers/Definitions/Nebulance.cs
src/NzbDrone.Core/Indexers/Definitions/PreToMe.cs
src/NzbDrone.Core/Indexers/Definitions/RevolutionTT.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentLeech.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentPotato/TorrentPotatoSettings.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentSeeds.cs
src/NzbDrone.Core/Indexers/Definitions/ZonaQ.cs
src/NzbDrone.Core/Notifications/Email/EmailSettings.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookSettings.cs

Fixed: Consistent help text and settings for Credential Fields
NO
- make password fields as privacy passwords
- consistent helptext and field labels
- make username fields as privacy username
- set username and password to NOT advanced
- N/A Tests
- N/A Translation Keys
- N/A Wiki Updates
* Fixes password in plain text for #252

Fixed: Correct Password and Username field Privacy

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
&authkey=xxxxx"
var authkey = 
@Qstick 
Added the additional test case for the authkey, fails current logic as expected
however, I can't figure out why the original message passes as not expected; pinged/linked to source on discord.

Fixed: Cleanse additional AuthKey instances in logs

---

frontend/src/Search/Table/CategoryLabel.js

NO
Not all results come back with a category so ui throws error since it's required for filtering 
example in AB: this result comes back with no category. there's a number of results that dont come back with one:
* Fixes #XXXX

Allow categories to be null on indexer search

---

frontend/src/Search/Table/CategoryLabel.js

NO
Builds off previous work in #301 , but instead of just displaying nothing, it instead shows a placeholder category that has a tooltip explaining to the user that they should report it, so it can get fixed.

If no categories are passed in, flag up a unknown error

---

src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs

NO
ImmortalSeed was returning results from all categories, but now respects category selection in Prowlarr searches.

Fixed: Respect categories for ImmortalSeed in search

---

src/NzbDrone.Core/Datastore/Migration/008_redacted_api.cs
src/NzbDrone.Core/Indexers/Definitions/Redacted.cs

YES - 008
Switch Redacted implementation over to API-based. Using Jackett, for example, will lead to IP bans. However, Lidarr's API implementation is stable and doesn't result in IP bans.
Implementation is based on Lidarr.
Re-opening this PR: https://github.com/Prowlarr/Prowlarr/pull/240 as I accidentally deleted the branch when attempting to squash commits.  My apologies!
* Fixes #76

New: (Indexers) (Redacted) Add API support

---

src/NzbDrone.Core/Indexers/Definitions/SubsPlease.cs

NO
I forgot this when i did #340, we should always convert to LocalDateTime when possible (value was still off by the offset due to not converting to local time)
* Fixes #XXXX

Fixed: (SubsPlease) fix offset release time issues

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
This changes mainly 3 things
1. Use Data classes instead of dynamic since its not only way more performant but also way more readable
2. It cleans up some parts and improves code consistency and also removes not used leftover comments from Jackett
3. It adds back the Episode padding for Sonarr compatibility
4. It fixes search queries by removing the Episode number as requesting with episode number will not return results
5. It Heavily improves Season searching by checking following things
`Anime Title 2nd Season` -> `S2`
`Anime Title 3rd Season` -> `S3`
`Anime Title 4th Season` -> `S4`
`Anime Title II` -> `S2`
`Anime Title III` -> `S3`
`Anime Title 2` -> `S2`
`Anime Title 3` -> `S3`
This last change **drastically** improves and fixes compatibility with Sonarr for season matching
I've …

Fixed: (AnimeBytes) cleanup code, fix episode searching & improve Season matching

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
Fixes a missing Converter declaration in the Group Model which can lead to a JSONException, also removes not used static Converter class

Fixed (AnimeBytes): apply LinksUnionConverter to model

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/RssParser.cs

NO
The Newsnab API of Anime Tosho also includes releases which have no NZB (either because its not processed yet or because it was handled before they started uploading to Usenet), i added filters which filter the releaes out if the Newsnab provider gives a type (which Anime Tosho does)
I tested it locally and it seems to not break any other Usenet indexer (tested with DrunkenSlug, NZBCat, SimplyNZBs)
* Fixes #200

Fixed (Anime Tosho): Only include Releases which have a NZB

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs

NO
Fixing individual episode searches from Sonarr with IPTorrents, making the results more accurate. A search will now take the shape of `+(imdbid) +(season/episode/search-term)`. I've tested that this does not exclude results, which it does not. However, without support for  for the season/episode format `SxY` (Example: `Title 1x10`) in `TvSearchCriteria.cs`, results will be partially incomplete. But only a minor subset of releases are labeled this way, and I believe that if this format is common enough to warrant inclusion in all TV episode searches, this should be handled in TvSearchCriteria, not per indexer.
I tried to apply a similar fix to TorrentLeech, but they don't allow searches that combine IMDbID and search term, like Iptorrents does so that didn't work out.
Note: 
* Fixes …

Iptorrents tv episode search fix

---

src/NzbDrone.Core/Indexers/Definitions/AlphaRatio.cs
src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/SecretCinema.cs

NO
Changed the Gazelle Request Generator so all Gazelle based indexers search using the full IMDB ID (tt1234567) where they previously used only the code without "tt" in front. I've verified that this is the de-facto standard across a range of Gazelle based indexers and confirmed this is the format Jackett have used for their indexers.
Other minor, but related fix includes removing the IMDB search capabiltiy for the Alpharatio indexer (Gazelle based) as this resulted in very poor results due to this tracker not tagging most releases with IMDb ID. Another fix was to add the IMDb capabilty for the Secret Cinema indexer (also Gazelle based).
* No issue reported. I noticed IMDb search was broken for the Secret Cinema indexer.

Fixed: Gazelle search using full IMDb ID

---

src/NzbDrone.Core/Indexers/Definitions/InternetArchive.cs

NO
Internet Archive might return results with some missing fields - this PR will solve those cases in the following way:
- if the InfoHash (btih) is missing: don't try to build and set a magnet url
- if the mediatype is missing (should not happen/never happened to me): assign "Other" category
* Fixes #401

[BugFix] (Tracker) Internet Archive: Add handling of missing result fields.

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
This PR changes two things
1. If an Episode is found, ignore the Season matching since it confuses Sonarr too much and Episodes are going by Absolute Numbering anyway
2. Makes all the Season guessing optional with an by default enabled Checkbox, since its really only working in 70% of all cases and still has a lot of false positives when Anime have Seasonal names with no Season number in it (Jojo for example with  stardust crusaders)
Before:
`TSUKIPRO THE ANIMATION 2 S2 4`
`Tensei Shitara Slime Datta Ken 2nd Season Part 2 S2 40`
Now:
`TSUKIPRO THE ANIMATION 2 04`
`Tensei Shitara Slime Datta Ken 2nd Season Part 2 40`
Not needed
None

Fixed: (Indexer) AnimeBytes improve sonarr compatibility and make optional

---

src/NzbDrone.Core/Indexers/Definitions/InternetArchive.cs

NO
Sorry for the inconvenience - I really hope I found it all now:
My implementation was missing the _FollowRedirect_ parameter (therefore Prowlarr missing the torrent file as it requires a redirect to the correct InternetArchive server).
This PR adds this parameter and lets Prowlarr fetch the file.

[BugFix] (Indexer) Internet Archive: Follow redirects.

---

src/NzbDrone.Core/Indexers/Definitions/BroadcastheNet/BroadcastheNet.cs

NO
The BroadcastTheNet indexer supports searching by Tvdb ids (and that support is already implemented in the code), but it didn't report that as a capability for tv search params.
This PR adds the TvSearchParams.TvdbId to the indexer, as well as TvSearchParams.RId (rage id).
- No issue reported

Fixed: (Indexer) BroadcastheNet - Report TvdbId and RId capability

---

src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornRequestGenerator.cs

NO
IMDBid search did not work because prowlarr was searching using the 1234567 imdbid instead of the "full" imdb id with tt in front, like tt1234567. I've modified it to use the latter, and tested that it works using radarr and the prowlarr search bar.
Similar issue to https://github.com/Prowlarr/Prowlarr/pull/389 but PTP is not Gazelle based so either fix do not affect each other.
* No reported issue. Only noticed by me.

Fixed: (Indexer) PTP IMDB search

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
This changes the API response model for AB to accept Links & Synonymns nullable since expecially for music there are none, when i implemented this change i also only tested with anime and not with music, should've probably tested both.
Not Needed
None, issue was brought up on Discord instead

Fixed: (Indexer) AnimeBytes Synonymns & Links are optional

---

src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBitsRequestGenerator.cs

NO
When sonarr searches for a tvshow, sometimes the tvdb might be null. The code today checks if tvdb == 0.. which means the search term is never applied as tvdb is null.
This fixed handles the searching properly.
* Fixes https://github.com/Prowlarr/Prowlarr/issues/437

Fixing HDBits not parsing the search term

---

src/NzbDrone.Core/Indexers/Definitions/ThePirateBay.cs

NO
- we were not generating a magnetlink from the infolink for TPB; thus TPB downloads were N/A
- N/A Tests
* Fixes Discord Issue

Fixed: (Indexer) TPB Missing Magnet Download Link & No Results for *arr Torznab

---

src/NzbDrone.Core/Indexers/Definitions/Xthor/Xthor.cs

NO
2.1s => 2.5s
- N/A Tests
* Fixes Logs of #472
```
2021-08-28 05:59:47.8|Error|Xthor|An error occurred while processing indexer feed. https://api.xthor.tk?passkey=(removed)&category=12%2B125%2B104%2B13%2B15%2B14%2B98%2B17%2B16%2B101%2B32%2B110%2B123%2B109%2B34%2B30&accent=1
[v0.1.1.875] System.Exception: Triggered AntiSpam Protection, please delay your requests!
at NzbDrone.Core.Indexers.Definitions.Xthor.XthorParser.CheckApiState(XthorError state) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Xthor\XthorParser.cs:line 112
at NzbDrone.Core.Indexers.Definitions.Xthor.XthorParser.ParseResponse(IndexerResponse indexerResponse) in …
```

Fixed: Increased Xthor Rate Limit Time

---

src/NzbDrone.Core/Indexers/Definitions/BakaBT.cs

NO?
As it stands the base url for BakaBT has &hentai=1
This breaks if a user does not have AdultContent enabled  in their bakabt settings.
Link to conversation in the discord
https://discord.com/channels/767843854736949299/767843854824374281/894437145849266176
None

Fixed: (Indexer) Changed BakaBT to default to SFW content

---

src/NzbDrone.Core/Indexers/Definitions/RevolutionTT.cs

NO
[REQ] is an automatically generated prefix added to the torrent title of a fulfilled request, and often breaks parsing for title matching. This causes it to not be picked up via RSS, and appears to be a mismatch with manual searches.

Fixed: (Indexer) RevolutionTT Remove [REQ] prefix from torrent title

---

src/NzbDrone.Core/Indexers/Definitions/TorrentLeech.cs

NO
- Torrentleech does not support additional parameters - like season and episode - if an IMDB/ID search is used.
- This causes garbage and unrelated results for sonarr episode and season searches
Fixed: (TorrentLeech) Drop support for IMDb ID TV Searches
Fixed: (TorrentLeech) Returning unrelated results for Season/Episode Searches
- NA Tests
- NA Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- NA [Wiki Updates](https://wiki.servarr.com)
* Fixes #474

Fix torrentleech tv searches returning unrelated results

---

src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs

based on Jackett f018470d6951a496b3d274fdda825c26ae8f6425
NO
jackett commit
```
rarbg: drop cat 35 ebook #12550
as the rarbg torrent search page no longer list this.
also drop book-search as there are not books anylonger to find.
```
* Fixes #XXXX

Fixed: (RarBG) Remove Book Category & Support

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
NZBGeek API key not cleansed
* Fixes #XXXX

Fixed: Cleanse APIKey from Newznab Response

---

frontend/src/Indexer/Add/AddIndexerModalContent.css
frontend/src/Indexer/Add/AddIndexerModalContent.js

**EDIT:** I just noticed #178 existed, this is realistically a duplicate of that.  It looks like that one is further along too so I can close this if its unnecessary.
NO
This PR adds a filter bar to the "Add Indexer" modal, which gives options for filtering the list by Protocol, Language, and Privacy Level.
This is my first PR to a *arr project, so I'm not sure if my coding style matches the rest of what the project is expecting. I am a React developer by trade, but I haven't used class components in a couple years. If you want to make big changes to how I did this, or just nix it and build this feature up from scratch, by all means go for it. The way I implemented it, the languages and privacy types are just built up from the list of indexers coming back, and I'm not sure if it would be …

Add a filter bar to the "Add Indexers" modal

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs

missed jackett commit https://github.com/Jackett/Jackett/commit/f5802306fa1fe4edb4c7f997100a6caebe71e989
Fixes #629
NO
@Qstick 
technically jackett has
`protected readonly string[] OptionalFields = { "imdb", "imdbid", "rageid", "tmdbid", "tvdbid", "poster", "description" };`
we have 
`protected readonly string[] OptionalFields = new string[] { "imdb", "imdbid", "rageid", "tmdbid", "tvdbid", "poster", "banner", "description" };`
should we be in sync or keep our extra for banner?
* Fixes #XXXX

Fixed: (Cardigann) Poster & tmbid are Optional by default

---

src/NzbDrone.Core/Indexers/Definitions/PrivateHD.cs

imdb search does not support S/E params
this matches the behavior for TorrentLeech
Fixes #119
NO
title
* Fixes #XXXX

Fixed: (PrivateHD) Drop support for IMDB search

---

src/NzbDrone.Mono.Test/Prowlarr.Mono.Test.csproj
src/NzbDrone.Mono/Prowlarr.Mono.csproj

NO
Use libMonoPosixHelper compiled against older glibc
* Fixes #XXXX

Fixed: Support older glibc in libMonoPosixHelper

---

src/NzbDrone.Core/Indexers/Definitions/HDTorrents.cs

YES - NO
Removes period from HDTorrent search strings.
* Fixes #687 
* Fixes [AB#2110](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2110)

Fixed: HDTorrents - remove . from searches

---

src/NzbDrone.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs
src/NzbDrone.Core/IndexerProxies/FlareSolverr/FlareSolverrSettings.cs

Closes #696
NO
Allows a user configurable timeout value between 1 and 180 seconds for Flaresolverr `maxTimeout` requests parameter
- Tests
-  https://github.com/Servarr/Wiki/commit/5005a63c5ba92a4700dc74f83cd882d0fb2c80d3
* Fixes #XXXX

New: (FlareSolverr Proxy) Configurable Request Timeout

---

src/NzbDrone.Core/Indexers/Definitions/DanishBytes.cs
src/NzbDrone.Core/Indexers/Definitions/PornoLab.cs

NO
- Fixed: (DanishBytes) Update Domain to .club
- Based on Jackett f890ddd119a35eb4ba40b407aa65461c713b5e5d
- Fixed: (PornoLab) Add new 2022 Categories
- Based on Jackett f61a2b47400e68422ba6620a5ef2f5b4d0a929a3
-  Tests
-  **We do not have Legacylinks supported for C# indexers it appears; do we need to do anything with the URL change?  DB Migration?  If we add support for Legacylinks for C#, I'll need some guidance for what to do.**

Jackett pulls - PornoLab and DanishBytes

---

src/NzbDrone.Core/Indexers/Definitions/TVVault.cs

Closes #573
NO
TV Vault does not support scraping
- Tests
- https://github.com/Servarr/Wiki/commit/51b60a5eac450a46adf87f51ab186fc5c584d6c3
* Fixes #XXXX

New: (TvVault) Mark as Obsolete per Site Bot Ban

---

src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgParser.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgTokenProvider.cs

* Added app_id to captcha check to avoid 403 forbidden error
* Migrated app_id from hard coded to BuildInfo.AppName
NO
Previously the captcha check threw an exception in the logs since Rarbg's API responds with 403 forbidden if `app_id` is skipped/overlooked in the query. I also took the opportunity to update `app_id` from hard coded to use the `BuildInfo.AppName` value instead.

Fixed: (Indexer) Update RARBG API query options

---

src/NzbDrone.Core/Indexers/Definitions/TorrentSeeds.cs

No need to C# implementation anymore
NO
Deprecate the TorrentSeeds' C# implementation, now that it uses UNIT3D
* Ref #732

TorrentSeeds is now using UNIT3D

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
AnimeBytes API does not support pagination, when a *arr now sends a request with an Offset Prowlarr normally would do paginate until it won't return any more results and then the *arr would stop, for AnimeBytes it would continue sending request with different Offsets but we would not include that in the request and always return the same response resulting in a lot of unnecessary requests to there api
This PR changes it so that if Offset in the request is provided and bigger than 0 it will not make an Request to AB but instead just return an empty list so that the *arr thinks Page 2 has no results anymore
In the future Prowlarr should have a mechanism like this build in for other Indexer which do not support pagination too, i've noted that down with a TODO comment above the line …

Fixed: (AnimeBytes) Do not paginate requests

---

src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs

NO
Fixes SpeedApp categories in requests by using NameValueCollection#GetQueryString `duplicateKeysIfMulti` parameter when building the query string
Mentioned on Discord by a User to me

Fixed: (SpeedApp) correct categories in query string of requests

---

src/NzbDrone.Core/Indexers/Definitions/MoreThanTV.cs
src/NzbDrone.Core/Parser/ParseUtil.cs

NO
Adds MoreThanTV C# indexer mostly taken from [Jackett](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/MoreThanTV.cs).
The implementation is as great as it can get right now, some stuff isn't working super well due to how the site handles things (when Torrents are grouped it will show the combined stats for Size/Seeders/Leechers etc for all of them so we have no way knowing the actual information for a single torrent of the group and just use the grouped info for all torrents) but that's kinda rare so overall it should be good to go until there API is ready.
None

New: (MoreThanTV) Add MoreThanTV

---

src/NzbDrone.Core/Indexers/Definitions/MoreThanTV.cs

NO
Somehow when using the non www domain it gets redirected which breaks the cookie, unsure exactly why but updating the url to the final redirect fixed the issue for me locally

Fixed: (MoreThanTV) use www url to fix cookie/redirect issues

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs

NO
- fixes nullref error if users have a cardigann url selected and there are no legacy links
- tested, works
- Tests
* Fixes #XXXX

Fixed: (Cardigann) Requests Failing for Definitions without LegacyLinks

---

src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs

NO
fixes discord report of current URL being 404 if search term is empty 
https://discord.com/channels/767843854736949299/767843854824374281/937155386664955946
* Fixes #XXXX

Fixed: (Immortalseed) Keywordless Search

---

src/Prowlarr.Http/Middleware/VersionMiddleware.cs

NO
Not sure if this is intentional or really harms anything but to be consistent with other Arr apps like Sonarr and Radarr, this changes the version header to X-Application-Version.

Set version header to X-Application-Version (missing hyphen)

---

src/NzbDrone.Core/Indexers/Definitions/RuTracker.cs

NO
The main rutracker.org is down at the time of writing. I am adding the official mirror rutracker.net, which is still up.
N/A
N/A
N/A

Add RuTracker.org mirror rutracker.net

---

src/NzbDrone.Core/Indexers/Definitions/Xthor/Xthor.cs

**NO**
Moved C# definition to Cardigan YAML v5 definition (https://github.com/Prowlarr/Indexers/pull/107)

indexer(xthor): moved to YAML definition v5

---

src/NzbDrone.Core/Indexers/Definitions/Anthelion.cs
src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/HDSpace.cs

based on jackett 22efff93e7f1df858b341b3c2756d8204cae6f4a
NO
Fixed: (Anthelion) Replace Periods for Space in Search Term
based on jackett 22efff93e7f1df858b341b3c2756d8204cae6f4a
Fixed: (HDSpace) Replace Periods for Space in Search Term
based on jackett 22efff93e7f1df858b341b3c2756d8204cae6f4a
Fixed: (Gazelle) Replace Periods for Space in Search Term
based on Jackett b8b816f953ad9d0508f95a9c31f9ff4385ebdd73
- Tests
* Fixes #XXXX

Jackett Pulls Anthelion and HDSpace

---

src/NzbDrone.Core/Indexers/Definitions/BeyondHD.cs

NO
- Changes logic to match cardigann for parsing tmdbid as long
- Fixes the below error reported in Discord.
```
2022-04-03 11:21:13.2|Warn|BeyondHD|Unable to connect to indexer
[v0.2.0.1448] System.OverflowException: Value was either too large or too small for an Int32.
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at NzbDrone.Core.Parser.ParseUtil.CoerceInt(String str) in D:\a\1\s\src\NzbDrone.Core\Parser\ParseUtil.cs:line 54
at NzbDrone.Core.Indexers.Definitions.BeyondHDParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\BeyondHD.cs:line 203
at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in …
```

Fixed: (BHD) TMDb Parsing Exception

---

frontend/src/Indexer/Index/Table/IndexerIndexRow.js

#834 #256 fix for unable to load the Indexes page
NO
Do not unload the DOM for a simple undefined property error.
Tested it with the Prowlarr backend and it works great.
Fix for this ![](https://user-images.githubusercontent.com/4707492/122823051-c717eb80-d2d6-11eb-9305-e5f5bcb387d7.png)
* Fixes #834 #256

#834 #256 fix for unable to load the Indexes page

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
A short attempt at fixing Prowlarr's handling of AnimeBytes `synonyms` field, when it failed to parse `Spy x Family` for me.
Example payload:
```json
"Synonymns":{"2":"SPYxFAMILY, Spy x Family"}
```
- Tests

Fixed: (AnimeBytes) Handle series synonyms with commas

---

frontend/src/Components/Chart/DoughnutChart.js
frontend/src/Components/Chart/StackedBarChart.js
frontend/src/Styles/Variables/colors.js

NO
On the Stats page, doughnut charts and stackedbar charts are currently unreadable because of the almost same yellow color for all items.
This PR brings a full range of differents colors for the items of those kind of charts.
Bar charts are not changed, they remain yellow with all bars the same color (maybe differents colors could be added in the futur when the order of items will be identical in all bar charts).
#232

Stats : diversify chartcolors for doughnut & stackedbar

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs

NO
The AltHub NZB indexer recently underwent some changes.  The existing URL returns a 403 error.
This commit updates the URL definition.
* Fixes #XXXX

Update AltHub API URL

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: Cleanse Notifiarr secret from URL in logs
(cherry picked from commit e6210aede6f7ead197e82572976bc0267d910d46)
(cherry picked from commit ec866082d44d299096112a6c7c232384b1f74505)
YES - XXXX | NO
* Fixes #XXXX

Fixed: Better Cleansing of Tracker Announce Keys

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs

Fixed: (Cardigann) Genre Parsing
New: (Cardigann) Add Validate Field Filter
v7
NO
- based on https://github.com/Jackett/Jackett/commit/a8b1001e9134f84049b1b78d584e20fe6f6c44be
- based on https://github.com/Jackett/Jackett/commit/44165e4534e7710bec58e48411a2c6c7bb294892
- based on https://github.com/Jackett/Jackett/commit/c820ebca0027c967d89a90de05e00ee4ea48c2bc
- based on https://github.com/Jackett/Jackett/commit/fa5a10f27c0382efde74051e17e2a1ce3f507409
- based on https://github.com/Jackett/Jackett/commit/f1b7f4fc250791ccacf5daa2ea30ad845d23cef8
- Tests
* Fixes #XXXX

Fixed: (Cardigann)  v7 Updates

---

src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

(cherry picked from commit d01bae92bfd68b04c54ab19bafe8af16c68ce711)

Fixed: Regex in log cleanser taking 10+ minutes on messages longer than 100k.

---

src/NzbDrone.Core/Indexers/Definitions/GreatPosterWall.cs

NO
Adds GreatPosterWall as a C# indexer with usage of the Gazelle base (a bit modified for there api response and freeleech token implementation)
I've tested the implementation successfully before and just waited for them to expose the original filename so that we can use it as a title, this implementation is also better than the current [Jackett Implementation](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/GreatPosterWall.cs) because it uses the original file names which are parsable by *arrs. 
Would still like other people to test this and see if it works as expected :)
see https://requests.prowlarr.com/p/torrent-great-poster-wallw
Closes #1086

New: (Indexer) GreatPosterWall

---

src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/GreatPosterWall.cs

NO
The default Gazelle implementation uses the `cataloguenumber` query parameter for imdb id searches which GPW doesn't support so if you use Prowlarr in combination with Radarr as example it would return useless results as GPW ignores that query parameter, i've made the gazelle methods protected so that i could override the request generator method for GPW in specific (also removed unused code still in gazelles default request generator)
Fixes issues brought up to me on Discord

Fixed: (GreatPosterWall) move imdb id search to searchstr query param

---

src/Prowlarr.Api.V1/Indexers/NewznabController.cs

NO
respond with 429 rate limit reached if the grab or query limit is met. This should improve backoff handling for downstream usage.
https://github.com/cross-seed/cross-seed/issues/327
- Tests
* Fixes #XXXX

New: Return 429 for Query and Grab Limits

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
This is a non breaking PR and only fixes compatibility with shows such as `Mob Psycho 100`
Example Current: `[SubsPlease] Mob Psycho 100 III 01 [Web][MKV][h264][1080p][AAC 2.0][Softsubs (SubsPlease)]`
Example New: `[SubsPlease] Mob Psycho 100 III - 01 [Web][MKV][h264][1080p][AAC 2.0][Softsubs (SubsPlease)]`
This fixes issues with Shows having numbers in there name but no delimiter of episodes so that Sonarr would parse the first number in the name which is the Shows name and not the episode and thus never grab valid releases
Issue was brought up to me on Discord

Fixed: (AnimeBytes) add delimiter to episode release

---

src/NzbDrone.Core/Indexers/Definitions/Torznab/Torznab.cs

NO
Removed suspicious URL from the code. Looks like the site that was originally there doesn't exist anymore and it's hosting malware (HD4Free.xyz).
none
- none

Removed suspicious URL in the default definitions

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
Adds three options to the animebytes indexer (turned on by default), allowing users to not include animebytes synonyms in search returns. 
@DevYukine 
#1191

Added setting to not include animebytes synonyms

---

src/NzbDrone.Core.Test/Files/Indexers/Newznab/newznab_caps.xml
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabCapabilitiesProviderFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabCapabilitiesProvider.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Indexers/Definitions/Torznab/Torznab.cs
src/NzbDrone.Core/Indexers/Definitions/Torznab/TorznabRssParser.cs

NO
Be smarter about mapping nab capabilities. Instead of simply using the id from the indexer and assuming it's going to match one of our standards, lets also compare by name. This allows us to better match those indexers which go by different Id standards without the need of maintaining ymls and such.
* Fixes #1117

New: Smarter Newznab category mapping

---

src/NzbDrone.Core/Applications/LazyLibrarian/LazyLibrarian.cs
src/NzbDrone.Core/Applications/Lidarr/Lidarr.cs
src/NzbDrone.Core/Applications/Mylar/Mylar.cs
src/NzbDrone.Core/Applications/Radarr/Radarr.cs
src/NzbDrone.Core/Applications/Readarr/Readarr.cs
src/NzbDrone.Core/Applications/Sonarr/Sonarr.cs
src/NzbDrone.Core/Applications/Whisparr/Whisparr.cs

NO
- there is no log indication nor obvious ui indication for why an indexer would not be synced to an app if the categories do not align.
- adds a trace line when add indexers are skipped to each app as a result of category mismatch
- Tests
* Fixes Chasing around settings to figure out why X did not sync or attempt to sync to Y

Log Skipped Application-Indexer Syncs at trace for support

---

src/NzbDrone.Common/Http/TooManyRequestsException.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgParser.cs

NO
- (Core) Add variable retryWait to TooManyRequestsException
- (Rarbg) don't try paging if rate_limit is populated
- (Rarbg) increase sleep from 2s to 4s
- (Rarbg) Treat 429 as TooManyRequests - backoff for 2 minutes
- (Rarbg) Treat 520 as TooManyRequests - backoff for 3 minutes
- (Rarbg) Treat 200 with rate_limt of 1 as TooManyRequests  - backoff for 5 minutes
@rarbg is this accurate as you expect?
- Tests
* Fixes #1169

Rarbg Rate Limiting

---

src/NzbDrone.Core/Indexers/Definitions/RetroFlix.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedApp/SpeedAppBase.cs

NO
- Added `TvSearchParam.ImdbId` to prevent unnecessary results. 
- Fixed the double slash the download link as well.

Fixed: (Indexer) Added "TvSearchParam.ImdbId" to SpeedApp

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs

NO
Fix to allow usage of template variables in selectors for cases like [this](https://github.com/Prowlarr/Indexers/blob/59be412d014e834eea6acd4b1f88cb042fe50e56/definitions/v7/thesceneplace.yml#L151).
Fixes Prowlarr/Indexers#287

Fixed: (Cardigann) Allow use of template variables in fields selector

---

src/NzbDrone.Core/Indexers/Definitions/RetroFlix.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedApp/SpeedAppBase.cs

Return 100 results and remove "[REQUESTED]" from title.
NO
- By default RetroFlix returns 10 results, while SpeedApp 50, this sets 100 for both.
- RetroFlix changed their MST to 5 days
- Removes `[REQUESTED]` from titles for RetroFlix

Fixed: (RetroFlix) Set 5 days as MST

---

src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazRequestGenerator.cs

not present when using "Accept: application/json"
NO

Fixed: (Avistaz) Workaround for fetching "retry-after" header 

---

src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazSettings.cs

Since it's a pain to reset your passkey, let's set it to be input of type hidden.
NO

Fixed: (Avistaz) Use type password for PID

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs

NO
The IPTorrents indexer doesn't currently handle offset searching and will hit the same page over and over again looking for more releases as a result:
<details>
<summary>log</summary>
```
2022-12-28 11:07:38.4|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-12-28 11:07:38.4|Info|ReleaseSearchService|Searching indexer(s): [IPTorrents] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5030, 5040, 5020, 5010, 5070]
2022-12-28 11:07:38.4|Debug|IPTorrents|Downloading Feed https://iptorrents.com/t?73=&26=&55=&78=&23=&24=&25=&66=&82=&65=&83=&79=&22=&5=&99=&4=&60=
2022-12-28 11:07:38.7|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [] for Season / Episode:[], …
```

Fixed: (IPTorrents) use offset to set page field

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannDefinition.cs

Just as a safe measure, use `RequestDelay` value only if it's greater than the inherited RateLimit (2s currently).
NO
* Fixes #1287

Fixed: (Cardigann) Apply RateLimit by using RequestDelay from definitions

---

src/NzbDrone.Core.Test/IndexerTests/AvistazTests/AvistazFixture.cs
src/NzbDrone.Core/Indexers/Definitions/AvistaZ.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazApi.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazBase.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazParserBase.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/CinemaZ.cs
src/NzbDrone.Core/Indexers/Definitions/ExoticaZ.cs
src/NzbDrone.Core/Indexers/Definitions/PrivateHD.cs

NO
AvistaZ was off by a large margin, so let's use the correct timezone offset for it. And in the future `TimezoneOffset` can be overwritten per tracker if needed.
Also some CS fixes, which I'll undo if they aren't necessary. 👍

Fixed: (AvistaZ) Use different timezone offset than the rest

---

frontend/build/webpack.config.js
package.json
yarn.lock

NO
chart.js v4 supports only modern browsers and so per [their recommendation](https://github.com/chartjs/Chart.js/issues/11028#issuecomment-1378391109) I'm allowing babel to transpile their library.
I'm getting `SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.` due to code like https://github.com/chartjs/Chart.js/blob/b2b881b9b104c4ce0699c64d8037c4b7fa7cae3e/src/core/core.datasetController.js#L224-L229
Related: chartjs/Chart.js#11028
Fixing the regex for extensions as well since I don't think you're planning to support `.j` files.

Fixed: (UI) Transpile chart.js to fix blank page on some browsers

---

src/NzbDrone.Core/Datastore/Migration/025_speedcd_userpasssettings_to_speedcdsettings.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedCD.cs

Database Migration
YES - 25
- `tvsearch` was searching only by `imdbid` returning all seasons and episodes available, and changed to if you search season `S02` it will lookup for `imdbid S02*` or `tvshow S02*`, `*` being wildcard. 
- Same for episode, thus if you search an episode it will return only that episode.
- I should mention that I left the wildcard for episodes too, since the worst that could happen is to return E10X for E10 and so on.
Hope it makes sense.

Fixed: (SpeedCD) Add wildcard to season in tvsearch, add freeleech toggle, improve query selectors

---

src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgParser.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgTokenProvider.cs

NO
I don't think it's in fact 1req/2s like they say in `apidocs_v2.txt`, I think they also use something like `token bucket algorithm` with a span of a few minutes.
- ~~Let's increase the RateLimit to 5s and to retry when `rate_limit=1` is in the error response.~~
- log why the parser didn't find any results.
/cc @bakerboy448

Fixed: (Rarbg) Add slash to IndexerUrl, increase RateLimit to 5s

---

src/NzbDrone.Core/Indexers/Definitions/AvistaZ.cs
src/NzbDrone.Core/Indexers/Definitions/CinemaZ.cs

NO
They'll remove the category on 31 January 2023.

Fixed: (AvistaZ/CinemaZ) Remove Music category mapping

---

src/NzbDrone.Core/Datastore/Migration/026_torrentday_cookiesettings_to_torrentdaysettings.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentDay.cs

YES - 25
Adds freeleech only setting.
I don't have an account to verify, but according to user's screenshot it only needs `;free` added for FL only search even if Jackett has `;free=on`. 
https://github.com/Prowlarr/Prowlarr/issues/1335#issuecomment-1386381234
* Fixes #1335

Fixed: (TorrentDay) Add freeleech only setting

---

src/NzbDrone.Core/Applications/Lidarr/Lidarr.cs
src/NzbDrone.Core/Applications/Radarr/Radarr.cs
src/NzbDrone.Core/Applications/Readarr/Readarr.cs
src/NzbDrone.Core/Applications/Sonarr/Sonarr.cs
src/NzbDrone.Core/Applications/Whisparr/Whisparr.cs
src/NzbDrone.Core/Indexers/IndexerTorrentBaseSettings.cs

NO
Sometimes the app's minimum seeders value isn't one size fits all for every indexer, so I think this would be a good addition to be able to set it per indexer if you'll like, with fallback to Sync profile's value.

New: Add apps minimum seeders per indexer

---

src/NzbDrone.Core/Indexers/Definitions/Nebulance.cs

NO
Currently `Three - Body` is transformed into `%Three%%%Body%`, with this change it would be ``%Three%Body%``

Fixed: (Nebulance) Use single wildcard in search

---

src/Prowlarr.Http/Frontend/Mappers/StaticResourceMapperBase.cs

NO
Serve plain text files as UTF-8, so as to ensure they are properly decoded by browsers.
* Fixes #1371

Serve plain text files (e.g. logs) as UTF-8.

---

src/NzbDrone.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs

NO
This drops some code passing userAgent to Flaresolverr. This has been kept around for Flaresolverr V1 compatibility but it's been almost a year and half that Flaresolverr v2 has been released and we are already at v3 now. Feel free to close this PR if you still want V1 support though.
* Fixes #949

Fixed: (Flaresolverr) no longer pass userAgent to FlareSolverr

---

frontend/src/Search/SearchFooter.js

NO
In the UI, if you search using the header input, the offset param continues to increase, even if you change the search terms. This gives unexpected search results (they're empty, since the backend doesn't like paged requests yet.) 
This fixes the search to reset the offset when you search via the header input.
1. Do a search
2. Do another search, via header (not footer)
N/A

Fixed: (UI) Reset header search offset value

---

src/NzbDrone.Core/Indexers/Definitions/PornoLab.cs

NO
This indexer was previously using the `infoUrl` as the download URL, which cases downloads to fail when validating the torrent. The UI would show the download as started, but it would never show up in the torrent client, and Prowlarr logs would show a torrent parsing error (because of course an HTML page is not a valid torrent).
This change updates the `DownloadUrl` property to actually point at the torrent URL, enabling search results from this indexer to be sent to the torrent client for download.

Fixed: (PornoLab) Use correct download URL

---

src/NzbDrone.Core/Applications/ApplicationService.cs

NO
improve logging;  users constantly have support issues with indexers not syncing to apps due to tags
`intersecting` and `handled` while accurate are not intuitive to users
- Tests
* Fixes Support Hell

Fixed: Clarify App Sync-Indexer Logging for tags

---

src/NzbDrone.Common.Test/ExtensionTests/IPAddressExtensionsFixture.cs
src/NzbDrone.Common/Extensions/IpAddressExtensions.cs
src/NzbDrone.Common/Options/AuthOptions.cs
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Configuration/ConfigService.cs
src/Prowlarr.Api.V1/Config/HostConfigResource.cs
src/Prowlarr.Http/Authentication/UiAuthorizationHandler.cs

(cherry picked from commit [4c41a4f368046f73f82306bbd73bec992392938b](https://github.com/Sonarr/Sonarr/commit/4c41a4f368046f73f82306bbd73bec992392938b))
NO
Added support for CGNAT IP ranges (100.64.0.0/10) to be optionally recognized as trusted addresses, allowing authentication bypass when accessing Prowlarr through CGNAT networks (like Tailscale), consistent with other local network behavior.
Configurable via config or PROWLARR__AUTH__TRUSTCGNATIPADDRESSES environment variable
* None

New: Add config file setting for CGNAT authentication bypass
