src/NzbDrone.Common/Http/CookieUtil.cs
src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs
src/NzbDrone.Common/Http/HttpResponse.cs
src/NzbDrone.Core.Test/HealthCheck/Checks/SystemTimeCheckFixture.cs
src/NzbDrone.Core.Test/IndexerTests/BasicRssParserFixture.cs
src/NzbDrone.Core.Test/IndexerTests/FileListTests/FileListFixture.cs
src/NzbDrone.Core.Test/IndexerTests/HDBitsTests/HDBitsFixture.cs
src/NzbDrone.Core.Test/IndexerTests/IPTorrentsTests/IPTorrentsFixture.cs
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabCapabilitiesProviderFixture.cs
src/NzbDrone.Core.Test/IndexerTests/NewznabTests/NewznabFixture.cs
src/NzbDrone.Core.Test/IndexerTests/NyaaTests/NyaaFixture.cs
src/NzbDrone.Core.Test/IndexerTests/PTPTests/PTPFixture.cs
src/NzbDrone.Core.Test/IndexerTests/RarbgTests/RarbgFixture.cs
src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssIndexerFixture.cs
src/NzbDrone.Core.Test/IndexerTests/TorrentRssIndexerTests/TorrentRssSettingsDetectorFixture.cs
src/NzbDrone.Core.Test/IndexerTests/TorznabTests/TorznabFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannConfigException.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/DateTimeUtil.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/IndexerStatusService.cs
src/Prowlarr.Api.V1/Indexers/IndexerResource.cs

NO
Port over ugly Jackett Login code for Cardigann Auth support

Cardigann auth

---

src/NzbDrone.Core/Notifications/Email/EmailSettings.cs

from radarr https://github.com/Radarr/Radarr/commit/f120b84c43a9ced3a225b6402baed433c546fc4e
NO
- Tests-N/A
- Translation Keys-N/A

Fixed: Allow "Pretty" From Address for Email

---

README.md

readme updates [skip ci]

---

.gitignore
frontend/src/Indexer/Index/Table/IndexerIndexRow.js
frontend/src/Indexer/Index/Table/IndexerStatusCell.js
frontend/src/Settings/Indexers/Indexers/EditIndexerModalContent.js
src/NzbDrone.Core/Datastore/Migration/003_indexer_props.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentPotato/TorrentPotato.cs
src/NzbDrone.Core/Indexers/Definitions/Torznab/Torznab.cs
src/NzbDrone.Core/Indexers/DownloadService.cs
src/NzbDrone.Core/Indexers/Events/IndexerDownloadEvent.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/IIndexer.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Indexers/IndexerDefinition.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/Prowlarr.Api.V1/Indexers/IndexerModule.cs
src/Prowlarr.Api.V1/Indexers/IndexerResource.cs

YES
Support per indexer setting to allow redirect or proxy on grabs. Also adds some logic to set which indexers this is allowed for (many need to proxy to get auth)

New: Support Indexer Grab Redirects

---

frontend/src/Components/Form/CardigannCaptchaInput.js
frontend/src/Components/Form/CardigannCaptchaInputConnector.js
frontend/src/Components/Form/FormInputGroup.js
frontend/src/Components/Form/ProviderFieldFormGroup.js
frontend/src/Helpers/Props/inputTypes.js
frontend/src/Store/Actions/captchaActions.js
src/NzbDrone.Common.Test/Http/HttpClientFixture.cs
src/NzbDrone.Common/Http/HttpRequest.cs
src/NzbDrone.Common/Http/HttpRequestBuilder.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Captcha.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannMetaDef.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/Prowlarr.Api.V1/Indexers/IndexerResource.cs
src/Prowlarr.Api.V1/ProviderControllerBase.cs

Captcha support

---

src/NzbDrone.Core/Localization/Core/en.json

.net core -> .net key

---

azure-pipelines.yml
src/NzbDrone.Automation.Test/Prowlarr.Automation.Test.csproj
src/NzbDrone.Common.Test/Prowlarr.Common.Test.csproj
src/NzbDrone.Core.Test/Prowlarr.Core.Test.csproj
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Prowlarr.Core.csproj
src/NzbDrone.Host.Test/Prowlarr.Host.Test.csproj
src/NzbDrone.Integration.Test/Prowlarr.Integration.Test.csproj
src/NzbDrone.Libraries.Test/Prowlarr.Libraries.Test.csproj
src/NzbDrone.Mono.Test/Prowlarr.Mono.Test.csproj
src/NzbDrone.Update.Test/Prowlarr.Update.Test.csproj
src/NzbDrone.Windows.Test/Prowlarr.Windows.Test.csproj
src/Prowlarr.Api.V1.Test/Prowlarr.Api.V1.Test.csproj

Fix memory leak

---

src/NzbDrone.Common/Composition/Extensions.cs

NO
Explicitly register concrete types as transient
* Hopefully the memory leak!

Fixed: Memory leak

---

src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs

New: ISO 8601 Date format in log files

---

frontend/src/Components/Page/Header/PageHeader.js

fix translate url

---

frontend/src/History/HistoryRowConnector.js

NO
Fixes the Search on History when URL Base is set. 
Issue reported via Discord - https://discord.com/channels/767843854736949299/833836262808354826/842846659687219200

Fixed: History search icon works with URL base set

---

src/NzbDrone.Core/Applications/Readarr/ReadarrSettings.cs

NO
Adds audiobook category support to Readarr to support audibooks within Readarr (as per current audiobook branch)

New: Added Audiobook categories for Readarr

---

frontend/src/System/Tasks/Queued/QueuedTaskRow.css
frontend/src/System/Tasks/Queued/QueuedTaskRow.js
src/NzbDrone.Common/Http/UserAgentParser.cs
src/NzbDrone.Core/Messaging/Commands/Command.cs
src/Prowlarr.Api.V1/Commands/CommandController.cs
src/Prowlarr.Api.V1/Commands/CommandResource.cs

NO
Show User Agent in System->Tasks for externally triggered commands - pulled from Sonarr

New: Show User Agent in System->Tasks for externally triggered commands

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

conflicted with radarr
NO
* Fixes #XXXX

Fixed: Change default SSL port to 6969 from 9898

---

src/Prowlarr.Http/Extensions/RequestExtensions.cs

NO
Fixes real IP logging in RP setups when IP is mapping IPv4 address as IPv6

Fixed: Real IP logging when IPv4 is mapped as IPv6

---

README.md
frontend/src/Components/FileBrowser/FileBrowserModalContent.js
frontend/src/Settings/General/UpdateSettings.js
frontend/src/Settings/Notifications/Notifications/NotificationEventItems.js
frontend/src/Store/Selectors/createHealthCheckSelector.js
frontend/src/System/Status/MoreInfo/MoreInfo.js
frontend/src/login.html
src/NzbDrone.Core.Test/HealthCheck/HealthCheckFixture.cs
src/NzbDrone.Core/Datastore/DbFactory.cs
src/NzbDrone.Core/HealthCheck/Checks/ApplicationStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/DownloadClientStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerLongTermStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/IndexerStatusCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/NewznabVIPCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/OutdatedDefinitionCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/ReleaseBranchCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/UpdateCheck.cs
src/NzbDrone.Core/HealthCheck/HealthCheck.cs
src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs
src/NzbDrone.Core/Notifications/Twitter/TwitterSettings.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/Prowlarr.Api.V1/ProviderResource.cs
src/Prowlarr.Api.V1/swagger.json

NO
Changes wiki links to wikijs.servarr.com, will revert to wiki.servarr.com once we push wikijs over after the Radarr/Sonarr redirects are in place.

Wikijs Links

---

.github/ISSUE_TEMPLATE/indexer_request.md

add indexer request template [skip ci]

---

src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs

NO
clarify help text
* Fixes #125

Fixed: MaM Helptext clarified

---

src/NzbDrone.Core/Localization/Core/en.json

NO
fixes missing keys 
-  Tests
* Fixes #XXXX

Fixed: Missing Translate Keys for Redirect & Help Text

---

src/NzbDrone.Core.Test/HealthCheck/Checks/ReleaseBranchCheckFixture.cs
src/NzbDrone.Core/HealthCheck/Checks/ReleaseBranchCheck.cs

Fixed: Develop branch invalid warning
NO
Fixes healthchecks for develop branch
* Fixes Reddit Post

Fixed: Develop branch out of date warning

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs

NO
Added the Usenet Indexer Newz-Complex

(Indexers) Add Newz-Complex

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
Fixed: Cleanse Token from logs
Fixed: Overzealous Log cleansing removing username= and password=
* Fixes #XXXX

Fixed: Log Cleansing

---

src/NzbDrone.Host/Startup.cs

NO
Respect `X-Forwarded-For` and `X-Forwarded-Proto` when creating redirect to the login page
* Fixes issue reported on discord

Fixed: Bad login redirect using a reverse proxy

---

src/NzbDrone.Core/Indexers/HttpIndexerBase.cs

NO
Reinstate original request URL after following redirections trying to log in
* Fixes #166

Fixed: Cardigann redirections after login

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Aither.cs

- Added support for Aither via Unit3d API
- Updated IndexerDefinitionUpdateService.cs

(Indexers) Add Support for Aither via UNIT3D API

---

src/NzbDrone.Core/Applications/Lidarr/LidarrIndexer.cs
src/NzbDrone.Core/Applications/Radarr/RadarrIndexer.cs
src/NzbDrone.Core/Applications/Readarr/ReadarrIndexer.cs
src/NzbDrone.Core/Applications/Sonarr/SonarrIndexer.cs

NO
- N/A Tests
- N/A Translation Keys
- N/A Wiki Updates
Fixes #196

Fixed: App not syncing correct if only Interactive Search enabled

---

src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs

Fix broken health check level so it is not always "Type" for Notifiarr connect

Fix broken health check level so it is not always "Type" for Notifiarr connect

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRequestGenerator.cs

NO
Fixes Newznab additional parameters not being appended to the search url.

Fixed: Newznab additional parameters

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs

YES | NO
TBD
Removes defunct indexer definitions.
- N/A Translation Keys
- N/A Wiki Updates
* Fixes #214

Fix remove Dead Usenet Indexers

---

frontend/src/Indexer/Stats/Stats.js

NO
Sorts average response times in chart on stats page.
N/A
N/A
N/A

Sort average response times

---

src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs

NO
Adds SpeedApp.io C# Indexer

(Indexers) Add SpeedApp C# indexer

---

src/Prowlarr.Api.V1/ProviderResource.cs

no
fix wiki link
n/a
todo: wiki eventually
* Fixes #XXXX

fix supported wikijs link

---

src/NzbDrone.Core/Indexers/Definitions/UNIT3D/Unit3dRequestGenerator.cs

NO
This fixes UNIT3D indexer running commit https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/f2c9281c4ee71e7c4003e7e2287d427b481747e9 and later, also i fixed wrong setting of tvdb id to tmdb id
* Fixes #XXXX

Fixed: add change to support both old and new UNIT3D indexer

---

README.md

read me updates [skip ci]

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs

NO
Allows users to add custom yml definitions in `Definitions/Custom` for super private indexers or testing ymls. The current logic will load up ymls in the folder only if they don't match name or file to an existing definition. 
* Fixes #99

New: Allow users to use custom ymls

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/Prowlarr.Api.V1/Indexers/IndexerResource.cs
src/Prowlarr.Api.V1/ProviderResource.cs

NO
- Fixes cardigann indexers missing description from API
- Fixes info link for indexers
- Tests
- Translation Keys
* Fixes #250

Schema api enhancements

---

src/NzbDrone.Core/Indexers/Definitions/BeyondHD.cs

NO
- Treat limited freeleech as freeleech
- finish todo now that the API is supposedly fixed
- correct the comment for min seed time
* Fixes: #268
* Closes: #269

Fixed:  (BHD) Treat Limited Freeleech as Freeleech

---

src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetSettings.cs

Title
-  Tests
- Translation Keys
- Wiki Updates
* Fixes #XXXX

Fixed: NZBGet Settings hint mentions Sabnzbd

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
fixed overzealous logs cleanse

Fixed: Incorrectly cleansing usetoken param

---

.github/ISSUE_TEMPLATE/bug_report.md

bug update [skip ci]

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Configuration/DeploymentInfoProvider.cs

NO
title
-  Tests
* Fixes @Qstick's oops 😛

Fixed: Default Branch is now Develop

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs

as of Jackett 4524c18d39251c677bec1d4d8f75f71c6c6ac010
NO
Add IPT alt links
- Tests
- Translation Keys
- Wiki Updates
* Fixes #XXXX

New: (Indexer) IPTorrents Alt Links

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
....yet again
* Fixes #XXXX

Fixed: Cleanse Pwd from logs

---

src/NzbDrone.Core/Localization/Core/en.json

NO
Title
- [Tests
* Fixes #XXXX

Fixed: Clarify redirect wording

---

CONTRIBUTING.md

fix radarr reference [skip ci]

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
Yet another log cleanse
* Fixes #XXXX

Fixed: Cleanse BHD APIKey from logs

---

src/NzbDrone.Core/Profiles/AppSyncProfileService.cs

NO
Old reference to movieService as parameter variable name in the dependencies

Updated movieService reference for App Sync Profile Service dependency on Indexer Factory

---

src/NzbDrone.Core/Indexers/Definitions/SubsPlease.cs

NO
Add alt link for Subsplease
-  Tests
* Fixes #325

New: (Indexer) SubsPlease Alt Links

---

.github/PULL_REQUEST_TEMPLATE.md

update pr temp [skip ci]

---

src/NzbDrone.Core/Indexers/Definitions/SubsPlease.cs

NO
Changes the request timezone to UTC, also simplifies some code and improves readability

Fixed: (SubsPlease) improve code readability, use UTC in request instead New York

---

src/Prowlarr.Api.V1/ProviderResource.cs

NO
Fix Supported-XXXX links
-  Tests
* Fixes #XXXX

Fixed: Provider Wiki Links (supported-X => supported#X)

---

src/NzbDrone.Core/Indexers/Definitions/TVVault.cs

New: (Indexer) TV Vault

---

.github/ISSUE_TEMPLATE/bug_report.md

(cherry picked from commit 4659a8366d8a1565890d3b72442bd35c6eb8176e)
git

Update bug report template [skip ci]

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs

ref https://www.reddit.com/r/prowlarr/comments/ojlamb/help_needed_with_ipt/h52nxnl/
NO
title
-  Tests
* Fixes #XXXX

Fixed: Improved IPT's Cookie Help Text

---

src/NzbDrone.Core/Indexers/Definitions/Anilibria.cs

NO
Adding anilibria C# indexer
* Fixes #XXXX
* Related https://github.com/Prowlarr/Prowlarr/issues/29

New: (Indexer) Anilibria

---

src/NzbDrone.Core/Localization/Core/en.json

Sentence used from https://wiki.servarr.com/prowlarr/indexers
NO
To clarify what to use if your indexer is not in the list to new users without having to look in the documentation.

Amend indexer list info

---

frontend/src/Search/Menus/SearchIndexSortMenu.js
frontend/src/Search/NoSearchResults.js
frontend/src/Search/SearchFooter.js
src/NzbDrone.Core/Localization/Core/en.json

NO
add missed translates
- Tests
* Fixes #XXXX

Fixed: Add Missing Search Translates

---

src/NzbDrone.Core/Indexers/Definitions/Shizaproject.cs

NO
Adding Shizaproject indexer support
Tests
Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
[Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX
* Related https://github.com/Prowlarr/Prowlarr/issues/29

New: (Indexer) Shizaproject

---

src/NzbDrone.Core/Indexers/Definitions/Animedia.cs

NO
Adds support for Animedia tracker
* Fixes #XXXX

New: (Indexer) Animedia

---

src/NzbDrone.Core/Indexers/Definitions/Anidub.cs

New: (Indexer) Anidub

---

CONTRIBUTING.md
README.md

git updates [skip ci]

---

src/NzbDrone.Core/Indexers/Definitions/TorrentDay.cs

NO
Add TorrentDay alt links
- N/A Tests
* Fixes #386

New: (Indexer) Alternative Links for TorrentDay

---

src/NzbDrone.Core/Indexers/Definitions/InternetArchive.cs

NO
Added support for Internet Archive as a tracker using their [Search API v1](https://archive.org/services/swagger/?url=%2Fservices%2Fsearch%2Fv1%2Fswagger.yaml#/search).
* Addresses https://github.com/Prowlarr/Prowlarr/issues/29#issue-837287949

New: (Indexer) Internet Archive

---

frontend/src/Indexer/Edit/EditIndexerModalContent.js
src/NzbDrone.Core/Indexers/Definitions/BinSearch.cs

NO
* Fixes [AB#67](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/67)

New: (Indexer) Binsearch

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
fixes overzealous cleansing.
* Fixes Discord issue

Fixed: Incorrectly Cleansing TorrentLeech Search URL

---

src/NzbDrone.Core/Applications/ApplicationBase.cs
src/NzbDrone.Core/Applications/Mylar/Mylar.cs

NO
- Fixed: {Mylar3) Indexer Host needs to include trailing /api 
- Fixed: Update AppIndexerRegex to support indexer ids over 100 
- Fixed Update AppIndexerRegex to support /api trailing (Mylar3)
- Tests  - we really should add app tests.  (how?)
* Fixes mylar issue reported via discord

Various Indexer/App fixes

---

frontend/src/Helpers/Props/icons.js
frontend/src/Indexer/Index/Table/IndexerStatusCell.js
frontend/src/Store/Actions/Creators/createHandleActions.js
src/NzbDrone.Core/HealthCheck/Checks/OutdatedDefinitionCheck.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/Prowlarr.Api.V1/swagger.json

NO
Replaces Blacklist with Blocklist (although this is not really used compared to other applications)

New: Renamed Blacklist to Blocklist

---

src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs

NO
Fix Rarbg url selection
* Fixes #441

Fixed: (Rarbg) Blank baseUrl drop-down

---

src/Prowlarr.Api.V1/Indexers/IndexerEditorController.cs

NO
Read from body for Delete method on IndexerEditor
* Fixes #275

Fixed: Mass Indexer delete fails with 415

---

frontend/src/Utilities/createAjaxRequest.js

fix mass delete

---

src/NzbDrone.Common.Test/Http/UserAgentParserFixture.cs
src/NzbDrone.Common/Http/UserAgentParser.cs

NO
hopefully fixes UA parsing.
New:
Old:
* Fixes #448

Fixed: UserAgent Parsing

---

.github/ISSUE_TEMPLATE/bug_report.yml

Git
Q do we have common to pull from prowlarr yet?

bug template fix [skip ci] [common]

---

frontend/src/Components/Page/Header/IndexerSearchInputConnector.js

NO
fixes
- N/A Tests
* Fixes #177

Fixed: Indexer Display Issue on Search Page

---

src/NzbDrone.Core/Indexers/Definitions/BroadcastheNet/BroadcastheNetRequestGenerator.cs

NO
- adds support for detecting daily series queries and passes them as-is without converting to int
- currently this fails as we try to convert the series to int
- check if the EpisodeSearchString matches `YYYY.MM.DD` via regex; if it does treat it as a daily series and pass it as-is w/o season
`2021-08-31 17:06:23.2|Debug|BroadcastheNet|Downloading Feed http://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Episode","Name":"2021.06.17","Search":"","Tvdb":"71256","Tvrage":"5714"}, 100, 0)`
Previously this would fail as `06/17` cannot be converted to an int and fails on pre-commit line 77
- N/A Tests
* Fixes #480

Fixed: (BTN) Daily Episode Searches failing

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
hoepfully cleanse post response for ygg
Ref #280 YGG Comment

Fixed: Better Log Cleansing

---

src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs

NO
check for http errors in mam response before trying to parse
use logic from gazelle
-  Tests
* Fixes 
https://gist.github.com/bakerboy448/ec4f1e03a5a26bcada96c4ed84f90bab

Fixed: (MAM) Don't Parse HTTP Error Responses

---

src/NzbDrone.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs
src/NzbDrone.Core/IndexerProxies/Http/Http.cs
src/NzbDrone.Core/IndexerProxies/HttpIndexerProxyBase.cs
src/NzbDrone.Core/IndexerProxies/Socks4/Socks4.cs
src/NzbDrone.Core/IndexerProxies/Socks5/Socks5.cs

NO
Q forgot, oops.
* Fixes #XXXX

Fixed: Missing Proxy Validation Translations

---

src/NzbDrone.Core/Indexers/Definitions/InternetArchive.cs

NO
API docs `movies: any item where the main media content is video files, like mpeg, mov, avi, etc`
- Tests
* Fixes Discord Request

New: (InternetArchive) Add Support for TV Categories

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/LatTeam.cs

NO
This should add support to lat-team.com which is based on unit3d.
I'd like some guidance on where to put the tests and if I should dump JSON from the api to use as mocked results.

New: (Indexer) Torrent lat-team.com

---

src/NzbDrone.Core/Indexers/Definitions/Headphones/Headphones.cs

NO
title
- Tests
* Fixes #XXXX

Fixed (Headphones): Add missing description

---

Convert-ProwlarrSupportedIndexersToMarkdownTable.ps1

Refactor Build => Supported Indexer Wiki Script

---

src/NzbDrone.Core.Test/ParserTests/ParseUtilFixture.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Anidub.cs
src/NzbDrone.Core/Indexers/Definitions/AnimeTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/Animedia.cs
src/NzbDrone.Core/Indexers/Definitions/Anthelion.cs
src/NzbDrone.Core/Indexers/Definitions/BB.cs
src/NzbDrone.Core/Indexers/Definitions/BakaBT.cs
src/NzbDrone.Core/Indexers/Definitions/BinSearch.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannDefinition.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/GazelleGames.cs
src/NzbDrone.Core/Indexers/Definitions/HDSpace.cs
src/NzbDrone.Core/Indexers/Definitions/HDTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs
src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs
src/NzbDrone.Core/Indexers/Definitions/Nebulance.cs
src/NzbDrone.Core/Indexers/Definitions/PreToMe.cs
src/NzbDrone.Core/Indexers/Definitions/RevolutionTT.cs
src/NzbDrone.Core/Indexers/Definitions/RuTracker.cs
src/NzbDrone.Core/Indexers/Definitions/SceneTime.cs
src/NzbDrone.Core/Indexers/Definitions/TVVault.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentSeeds.cs
src/NzbDrone.Core/Indexers/Definitions/ZonaQ.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
src/NzbDrone.Core/Parser/ParseUtil.cs

NO
Updates to Cardigann
- New `AllowRawSearch` property in caps
- Improve Size, Int, Long Parsing and movie to ParseUtil
- Add tests for Size parsing
Closes #485

Cardigann 2.0

---

src/NzbDrone.Core/Indexers/Definitions/Anilibria.cs

NO
Fix redirect problem when downloading torrent files
* Fixes #XXXX

Anilibria: Fix download torrent link

---

src/NzbDrone.Core.Test/HealthCheck/HealthCheckServiceFixture.cs
src/NzbDrone.Core/HealthCheck/HealthCheckService.cs
src/NzbDrone.Core/HealthCheck/ServerSideNotificationService.cs

NO
Support for simple server health notifications. Uses endpoint created by https://github.com/Servarr/ServarrAPI.Update/pull/25

New: Support server notifications

---

src/NzbDrone.Core/Indexers/Definitions/DesiTorrents.cs

Closes #562
NO
Title
-  Tests
* Fixes #XXXX

New: (DesiTorrents) Add Alt URL .rocks

---

src/NzbDrone.Core/Indexers/Definitions/BakaBT.cs

NO
Typo in  link added a space between https://bakabt.me/ and browse.php? if adult content not checked
* Fixes #

Fixed: (Indexer) Fix Typo in BakaBT

---

src/NzbDrone.Core/Indexers/Definitions/RuTracker.cs

Fixed: (RuTracker.Org) Fails to add

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs
src/NzbDrone.Core/Prowlarr.Core.csproj

NO
Adds syslog forwarding for logs via UDP
The following logs show up prior to the syslogging being initiated

New: Added UDP syslog support

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixes #557
NO
title
* Fixes #XXXX

Fixed: (Avistaz) Cleanse PID & Hash from response

---

frontend/src/Store/Actions/systemActions.js
frontend/src/System/Events/LogsTableRow.js

(cherry picked from commit c14ef7bee7477ad5d29498f1cba94267eb11daf0)
NO
Moves time/date column on events page  (already done on Radarr)

Fixed: Time column is first column on events page

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs

Fixed: Remove Defunct Usenet Indexer NZBXS

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: Cleanse RSSKey and PassKey from Indexer Response

---

src/NzbDrone.Core/HealthCheck/Checks/OutdatedDefinitionCheck.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Aither.cs
src/NzbDrone.Core/Indexers/Definitions/AnimeWorld.cs
src/NzbDrone.Core/Indexers/Definitions/Blutopia.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannDefinition.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequest.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/DesiTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/DigitalCore.cs
src/NzbDrone.Core/Indexers/Definitions/InternetArchive.cs
src/NzbDrone.Core/Indexers/Definitions/Milkie.cs
src/NzbDrone.Core/Indexers/Definitions/ShareIsland.cs
src/NzbDrone.Core/Indexers/Definitions/SuperBits.cs
src/NzbDrone.Core/Indexers/Definitions/ThePirateBay.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentLeech.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentParadiseMl.cs
src/NzbDrone.Core/Indexers/Definitions/YTS.cs
src/NzbDrone.Core/Indexers/IIndexer.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/NzbDrone.Core/Parser/ParseUtil.cs
src/NzbDrone.Core/ThingiProvider/IProvider.cs

NO
Support for JSON API parsing in Cardigann
Fixes #550

New: Support JSON parsing in Cardigann

---

src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs

Closes #592
NO
Orpheus won't download if useToken=0
* Fixes #XXXX

Fixed: Orpheus failing to grab if token is not used

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs

NO
- fixes and future proofs logging of rsskey/apikey from cardigann config
- fixes not using the api key in headers for searches
- Tests
* Fixes #606

Cardigann v3 fixes

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Prowlarr.Core.csproj

NO
Enables XML parsing with filters for Cardigann

New: (Cardigann) XML Parser Suppport

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
(cherry picked from (Readarr PR) commit 571b4647702737858d890ec2d18b73703b4b5a88)
* Fixes #XXXX

Fixed: Cleanse APIKey from Signalr logging 

---

src/NzbDrone.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs

NO
lowercase keys `server` =! header key of `Server`
* Fixes #XXXX

Fixed: (FlareSolverr) Detection of Cloudflare

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: (RarBG) Do not cleanse get_token

---

src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs

Fixed: (Orpheus) Try to actually use the token

---

.github/ISSUE_TEMPLATE/bug_report.yml

(cherry picked from commit beb22844c960db8e0f42a32809ad74cffce06e09)
git

Update Github Templates [skip ci]

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

cleanse postgres username/pass creds

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs

Block the old non-v3 indexers

---

src/NzbDrone.Core/HealthCheck/Checks/OutdatedDefinitionCheck.cs

Fixed: Outdated Definition Healthcheck not using Definition Name

---

src/NzbDrone.Core/Indexers/Definitions/Xthor/XthorParser.cs

NO
replace `api.` with nothing
- Tests
* Fixes #577

Xthor info link

---

src/NzbDrone.Core/Indexers/Definitions/TorrentSyndikat.cs

Fixed: (TorrentSyndikat) Download URL missing API

---

src/NzbDrone.Core/Indexers/Definitions/PornoLab.cs

New: (Indexer) PornoLab

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixes #652
NO
title
* Fixes #XXXX

Fixed: (UNIT3D Indexers) Cleanse RID in Logs 

---

src/NzbDrone.Host/Bootstrap.cs

fix erroneous logging for windows service on non-windows

---

src/NzbDrone.Common/Extensions/PathExtensions.cs
src/NzbDrone.Host/Bootstrap.cs
src/NzbDrone.Host/Startup.cs

(cherry picked from commit a219b4a1b869863b2ef47d4bdf33d308cb261ba3)
Fixes #409
NO
* Fixes #XXXX

Fixed: Forms login persists across restarts in docker

---

src/NzbDrone.Core/Indexers/Definitions/Anilibria.cs

Mark C# Anilibria as obsolete
NO
title
- Tests
* Fixes #XXXX

Fixed: (Anilibria) Duplicate entries

---

src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs

Change out Comedy and E-Learning Videos categories to Other category
YES - XXXX | NO
* Fixes #XXXX

Update Orpheus categories -> Prior Movie/TV mappings => Other

---

src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs

Remove TV and Movie categories from orpheus indexer
YES - XXXX | NO
* Fixes #XXXX

Update Orpheus Search Caps - Drop Movie and TV Support

---

src/NzbDrone.Core/Indexers/Definitions/BB.cs

based on jackett fbb1f15d7014b2d8c23c6ee94c2bcf37612066db
NO
title
* Fixes #711

Fixed: (BB) Remove '.' from Search String

---

src/NzbDrone.Core/Indexers/Definitions/Aither.cs
src/NzbDrone.Core/Indexers/Definitions/AnimeWorld.cs
src/NzbDrone.Core/Indexers/Definitions/Blutopia.cs
src/NzbDrone.Core/Indexers/Definitions/DesiTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/DigitalCore.cs
src/NzbDrone.Core/Indexers/Definitions/InternetArchive.cs
src/NzbDrone.Core/Indexers/Definitions/Milkie.cs
src/NzbDrone.Core/Indexers/Definitions/ShareIsland.cs
src/NzbDrone.Core/Indexers/Definitions/SuperBits.cs
src/NzbDrone.Core/Indexers/Definitions/ThePirateBay.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentLeech.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentParadiseMl.cs
src/NzbDrone.Core/Indexers/Definitions/YTS.cs

fixup add rationale for Obsolete of C# Indexer Implementations - resolves code smells

---

src/NzbDrone.Core/Localization/Core/en.json

Fix misleading Tags helptext [skip ci]

---

src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs

https://api.drunkenslug.com gives a 301
NO
-  Tests
* Fixes #XXXX

Fixed: (Usenet) (DrunkenSlug) Update URL

---

azure-pipelines.yml

Bump 0.1.9

---

azure-pipelines.yml

Auto api docs

---

frontend/src/Indexer/Add/AddIndexerModalContent.js
src/NzbDrone.Core/Indexers/Definitions/Anidub.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/NzbDrone.Core/Indexers/IndexerPrivacy.cs
src/NzbDrone.Core/Localization/Core/en.json

NO
Fixed incorrect enum and related
- Tests
* Fixes #XXXX

Fixed: SemiPublic => SemiPrivate

---

src/NzbDrone.Core/Indexers/Definitions/TorrentLeech.cs

Closes #720
NO
Title
- Tests
* Fixes #XXXX

Fixed: (TorrentLeech) Calculating Incorrect Age

---

frontend/src/index.ejs
frontend/src/login.html

NO
Set `theme-color` to Prowlarr's logo color.
* Fixes #XXXX

Set frontend `theme-color` to logo color

---

src/NzbDrone.Core/Indexers/Definitions/DanishBytes.cs

based on jackett bac28c030295bddeb2cc7934da6257dd013d8f60
NO
title
* Fixes #XXXX

New: (DanishBytes) Add .org Alt Link

---

src/NzbDrone.Core/Configuration/ConfigFileProvider.cs

NO
Fixes default postgres port

Fixed: Postgres default port

---

src/NzbDrone.Core/Download/DownloadMappingService.cs
src/NzbDrone.Core/Indexers/Definitions/BakaBT.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs
src/NzbDrone.Core/Indexers/Definitions/TorrentLeech.cs
src/Prowlarr.Api.V1/Indexers/NewznabController.cs
src/Prowlarr.Api.V1/Search/SearchController.cs

NO
Change URL encoding to properly encode all non-ascii characters
* Fixes #779

Rework URL Encoding

---

src/NzbDrone.Core/Indexers/Definitions/PornoLab.cs

NO
title
- Tests
* Fixes #XXXX

Fixed: (PornoLab) Update Privacy to Semi-Private

---

src/NzbDrone.Core/Indexers/Definitions/RuTracker.cs

NO
title
- Tests
* Fixes #XXXX

Fixed: (RuTracker org) Update Privacy to Semi-Private

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs

NO
Only make one call for indexer updates, grab and unpack in 0.7sec
```
2022-01-20 22:56:33.2|Trace|CommandExecutor|IndexerDefinitionUpdateCommand -> IndexerDefinitionUpdateService
2022-01-20 22:56:33.2|Trace|CommandQueueManager|Marking command as started: IndexerDefinitionUpdate
2022-01-20 22:56:33.3|Debug|ManagedHttpDispatcher|Downloading [https://indexers.prowlarr.com/master/4/package.zip]
2022-01-20 22:56:33.6|Debug|ManagedHttpDispatcher|Downloading Completed. took 0s
2022-01-20 22:56:34.0|Debug|IndexerDefinitionUpdateService|Updated indexer definitions
2022-01-20 22:56:34.1|Trace|CommandExecutor|IndexerDefinitionUpdateCommand <- IndexerDefinitionUpdateService [00:00:00.7659208]
```
* Fixes #791

Optimize Indexer updates

---

src/NzbDrone.Core/Localization/Core/en.json

NO
Added missing translate for Database (used in UI about.js)

Fixed: Added missing translate for Database

---

src/NzbDrone.Core/Download/Clients/rTorrent/RTorrentSettings.cs

NO
Updated helptext on adding torrents to ruTorrent in a stopped state.
* Fixes #XXXX

Fixed: Updated ruTorrent stopped state helptext

---

frontend/src/Indexer/Index/Table/IndexerIndexRow.js
src/NzbDrone.Core/Datastore/Migration/015_indexer_versions.cs
src/NzbDrone.Core/Datastore/TableMapping.cs
src/NzbDrone.Core/HealthCheck/Checks/NoDefinitionCheck.cs
src/NzbDrone.Core/HealthCheck/Checks/OutdatedDefinitionCheck.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionVersion.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionVersionRepository.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionVersionService.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/IndexerFactory.cs
src/NzbDrone.Core/Localization/Core/en.json
src/Prowlarr.Api.V1/Indexers/IndexerResource.cs

YES (15)
Database table for indexer definition versions, selective updating if server has changed
Don't hide indexer that don't have a definition
HealthCheck indexers with deleted or missing definition
Fallback to disk if no server response to AllDef endpoint

Misc definition handling improvements

---

src/NzbDrone.Core/Indexers/IndexerBaseSettings.cs

NO
see commit msg
- Tests
* Fixes #XXXX

Fixed: Corrected Query Limit and Grab Limit HelpText

---

src/NzbDrone.Core/Indexers/Definitions/BeyondHD.cs

Fixed: (BHD) Handle API Auth Errors

---

src/NzbDrone.Core/Indexers/Definitions/AnimeWorld.cs

NO
Updates the categories to match the one on the site

Update Categories - AnimeWorld

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannDefinition.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequest.cs

NO
Bumps Cardigann to v5
Adds support for filters on json response parsing
Moves `Attribute` and `Multiple` property 
* Fixes #844
* Closes #848

New: (Cardigann) Allow JSON filters

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: Cleanse Tracker api_token from logs

---

src/NzbDrone.Core/Indexers/Definitions/PornoLab.cs

NO
"Oops" - Qstick probably
* Fixes #XXXX

Fixed:(pornolab) language formatting

---

src/NzbDrone.Core/Indexers/Definitions/DanishBytes.cs

NO
Title
- Tests
* Fixes #XXXX

New: (DanishBytes) Move to YML

---

frontend/src/Components/Link/Link.js

(cherry picked from commit 140547e42a32cbaf80e7a794c5be9bfb574e97a2)
NO
- Tests
* Fixes Discord Report

Fixed: '/indexers' URL Base breaking UI navigation

---

src/NzbDrone.Core/Indexers/Definitions/Redacted.cs

indexer does not actually have movies and tv
NO
make @Davo1624's Prowlarr Instance happier and not sync RED to Radarr
- Tests

Fixed: (Redacted) Map Categories Comedy & E-Learning Videos to 'Other'

---

src/NzbDrone.Update/UpdateEngine/DetectExistingVersion.cs

Closes #873
(cherry picked from commit bc3e3714b97dec19091e45324d9f2b550f1dbbd5)
NO
* Fixes #877
* Fixes #873

Fixed: Update from version in logs

---

frontend/src/Indexer/Info/IndexerInfoModalContent.js

Fixed: Indexer Infobox Error

---

src/NzbDrone.Core/Backup/BackupService.cs
src/NzbDrone.Core/Datastore/Converters/TimeSpanConverter.cs
src/NzbDrone.Core/Datastore/TableMapping.cs

NO
common pulls
- Tests
* Fixes #XXXX

Servarr pulls

---

src/NzbDrone.Core/Applications/Lidarr/LidarrV1Proxy.cs
src/NzbDrone.Core/Applications/Radarr/RadarrV3Proxy.cs
src/NzbDrone.Core/Applications/Readarr/ReadarrV1Proxy.cs
src/NzbDrone.Core/Applications/Sonarr/SonarrV3Proxy.cs
src/NzbDrone.Core/Applications/Whisparr/WhisparrV3Proxy.cs

NO
- Warn users that a base url may be missing for \*Arrs
- Improved Validation Errors for \*Arr Tests
- Add Sonarr v2 note
* Closes https://github.com/Prowlarr/Prowlarr/issues/502

New: (Lidarr/Radarr/Readarr/Sonarr) Improved Errors

---

src/NzbDrone.Core/Indexers/Definitions/BroadcastheNet/BroadcastheNet.cs
src/NzbDrone.Core/Indexers/Definitions/BroadcastheNet/BroadcastheNetParser.cs

NO
see commit msg
- Tests
* Fixes #XXXX

Fixed: Handle BTN Responses and Rate Limiting

---

src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBitsParser.cs
src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornParser.cs

NO
see commit msg
- Tests
* Fixes #798

Fixed: (PTP) (HDBits) Treat 403 as Query Limit

---

src/NzbDrone.Core/Indexers/Definitions/MoreThanTV.cs

NO
Updates MoreThanTV's browse endpoint and fixes HTML query selectors.
* Fixes #922 
* Fixes #788

Fixed: MoreThanTV indexer from browse page layout changes (#788, #922)

---

src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs

New: MyAnonamouse freeleech support

---

src/NzbDrone.Core/Indexers/Definitions/HDTorrents.cs

NO
Search imdbid + season/episode

Fixed: (Indexer) HDTorrents search imdbid + season/episode

---

src/NzbDrone.Core/Indexers/Definitions/ExoticaZ.cs

based on jackett fa2025cfd4b538d24a4a11bec6f5b13f8711fce0
NO
- Tests
* Fixes #938

Fixed: (exoticaz) Category Parsing

---

src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
- Tests - N/A - add additional sites to regex
* Fixes #939

Fixed: (CinemaZ, ExoticaZ, PrivateHD) Better Indexer Response Log Cleansing

---

src/NzbDrone.Core/Indexers/Definitions/TorrentDay.cs

Fixes no S/E
Fixes #816
NO
* Fixes #XXXX

Fixed: (TorrentDay) TV Search

---

src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs

NO
see commit msg
- Tests
* Fixes #XXXX

Fixed: (MaM) Handle Auth Errors & Session Expiry

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: (MoreThanTV) Better Response Cleansing

---

src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs

NO
Typo for myanonamouse.
https://cdn.discordapp.com/attachments/764440599621009410/970114071355621426/Screen_Shot_2022-04-30_at_5.06.52_PM.png
* Fixes #XXXX

Typo for myanonamouse.

---

src/NzbDrone.Core/Indexers/Definitions/BroadcastheNet/BroadcastheNet.cs

Fixes #979
NO
sonarr and jackett both use HTTPS as well
* Fixes #XXXX

Fixed: (BTN) Move to HTTPS

---

src/NzbDrone.Core/Localization/Core/en.json

Fixed: Indexer Tags Helptext

---

frontend/src/App/App.js
frontend/src/Components/Page/PageContent.js
frontend/src/Settings/General/HostSettings.js
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Instrumentation/ReconfigureLogging.cs
src/NzbDrone.Core/Localization/Core/en.json
src/NzbDrone.Core/Validation/RuleBuilderExtensions.cs
src/Prowlarr.Api.V1/Config/HostConfigController.cs
src/Prowlarr.Api.V1/Config/HostConfigResource.cs
src/Prowlarr.Api.V1/System/SystemController.cs
src/Prowlarr.Http/Frontend/InitializeJsController.cs

NO
Allows setting of instance name, also sets up syslog level to be independent of log level

Syslog and Instance Name Updates

---

src/NzbDrone.Core/IndexerSearch/NewznabResults.cs

NO
add description element in nab response

New: Send description element in nab response

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixes #1041
NO
title
* Fixes #XXXX

Fixed: (AnimeBytes) Cleanse Passkey from response

---

frontend/src/Search/QueryParameterModal.js
src/NzbDrone.Core.Test/IndexerTests/CardigannTests/ApplyGoTemplateTextFixture.cs
src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/IndexerSearch/NewznabResults.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Anthelion.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs
src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs

NO
DoubanId
TmdbId for TV
Range Index
* Fixes #989 
* Fixes #990 
* Fixes #997 
* Fixes #1020
* Fixes #1036

V6 Cardigann Changes

---

azure-pipelines.yml
src/NzbDrone.Automation.Test/AutomationTest.cs
src/NzbDrone.Common.Test/ProcessProviderFixture.cs
src/NzbDrone.Common.Test/ServiceFactoryFixture.cs
src/NzbDrone.Common/Processes/ProcessProvider.cs
src/NzbDrone.Core.Test/Datastore/DatabaseFixture.cs
src/NzbDrone.Core.Test/Framework/DbTest.cs
src/NzbDrone.Core.Test/Framework/DbTestCleanup.cs
src/NzbDrone.Core.Test/Framework/TestDatabase.cs
src/NzbDrone.Core.Test/Housekeeping/Housekeepers/FixFutureRunScheduledTasksFixture.cs
src/NzbDrone.Core/Configuration/ConfigFileProvider.cs
src/NzbDrone.Core/Datastore/BasicRepository.cs
src/NzbDrone.Core/Datastore/PostgresOptions.cs
src/NzbDrone.Core/Datastore/WhereBuilderPostgres.cs
src/NzbDrone.Host.Test/ContainerFixture.cs
src/NzbDrone.Host/Bootstrap.cs
src/NzbDrone.Integration.Test/IntegrationTest.cs
src/NzbDrone.Mono.Test/DiskProviderTests/SymlinkResolverFixture.cs
src/NzbDrone.Test.Common/Datastore/PostgresDatabase.cs
src/NzbDrone.Test.Common/Datastore/SqliteDatabase.cs
src/NzbDrone.Test.Common/NzbDroneRunner.cs
src/NzbDrone.Test.Common/TestBase.cs
src/postgres.runsettings

NO
Runs Integration tests against Postgres database

Running Integration Tests against Postgres Database

---

src/NzbDrone.Common.Test/DiskTests/DiskProviderFixtureBase.cs
src/NzbDrone.Common.Test/DiskTests/DiskTransferServiceFixture.cs
src/NzbDrone.Common.Test/DiskTests/FreeSpaceFixtureBase.cs
src/NzbDrone.Common/Disk/DiskProviderBase.cs
src/NzbDrone.Common/Disk/DiskTransferService.cs
src/NzbDrone.Common/Disk/IDiskProvider.cs
src/NzbDrone.Common/Disk/LongPathSupport.cs
src/NzbDrone.Core.Test/UpdateTests/UpdateServiceFixture.cs
src/NzbDrone.Core/Update/InstallUpdateService.cs
src/NzbDrone.Core/Validation/FolderChmodValidator.cs
src/NzbDrone.Mono.Test/DiskProviderTests/DiskProviderFixture.cs
src/NzbDrone.Mono.Test/DiskProviderTests/FreeSpaceFixture.cs
src/NzbDrone.Mono/Disk/DiskProvider.cs
src/NzbDrone.Mono/Disk/FindDriveType.cs
src/NzbDrone.Update/UpdateEngine/InstallUpdateService.cs
src/NzbDrone.Windows.Test/DiskProviderTests/FreeSpaceFixture.cs
src/NzbDrone.Windows/Disk/DiskProvider.cs

Update file and folder handling methods from Radarr

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

NO
`/` do not need to be escaped
- fixes tests
- fixes regex
- 
* Fixes #XXXX

Fixed: Log Cleanse Indexer Response Logic and Test Cases

---

src/NzbDrone.Common/Prowlarr.Common.csproj
src/NzbDrone.Core/Prowlarr.Core.csproj

NO
Bump some deps, test some things

Bump Mailkit to 3.3.0

---

src/NzbDrone.Core/IndexerSearch/Definitions/BookSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/Definitions/TvSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/NewznabRequest.cs
src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs
src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs
src/NzbDrone.Core/Indexers/IndexerCapabilities.cs
src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs

NO
Bump to v7 Schema, Support more queries

New: (Cardigann) Additional query support

---

src/NzbDrone.Core/Download/Clients/Hadouken/HadoukenProxy.cs
src/NzbDrone.Core/Download/Clients/Nzbget/NzbgetProxy.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV1.cs
src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs
src/NzbDrone.Core/Download/Clients/Transmission/TransmissionProxy.cs
src/NzbDrone.Core/Download/Clients/uTorrent/UTorrentProxy.cs

NO
Changes from de243991dd78c0fa4cfd2b629839874bbd8f2650 missed b7b5a6e7e1150e2a34aac37deff84f02840111cf
* Fixes #XXXX

Support for digest auth with HttpRequests

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs

based on jackett 9768fd288ba299f8a2d1aada1a539d156e7e97b9
NO
https://github.com/Jackett/Jackett/commit/9768fd288ba299f8a2d1aada1a539d156e7e97b9
* Fixes #XXXX

Fixed: (Cardigann) fix imatch for rows

---

src/NzbDrone.Common/Http/HttpResponse.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs

NO
Try and fix M-team
Closes #1103
Fixes #1061

Warn on redirect to alt domain when checking if login required

---

src/NzbDrone.Common/Prowlarr.Common.csproj
src/NzbDrone.Core.Test/Prowlarr.Core.Test.csproj
src/NzbDrone.Core/Prowlarr.Core.csproj

Bump YamlDotNet to 12.0.1

---

src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/GreatPosterWall.cs

NO
use`virtual`/`override` instead of `new` so that the correct method is called

Fixed: (GreatPosterWall) correctly override Gazelle base method

---

src/NzbDrone.Core/Localization/Core/pt.json
src/NzbDrone.Core/Localization/Core/zh_TW.json

Translations update from [Servarr Weblate](https://translate.servarr.com) for [Servarr/Prowlarr](https://translate.servarr.com/projects/servarr/prowlarr/).
Current translation status:

Translations update from Servarr Weblate

---

src/NzbDrone.Core/Indexers/Definitions/RetroFlix.cs

Fixes #1159
NO
.net to .club
-  Tests
* Fixes #XXXX

Fix: (RetroFlix) Update URL to .club

---

azure-pipelines.yml

Re-enable freebsd11 tests now agent updated

---

src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs

NO
This implements support for AnimeBytes api change including a FileList in the api response, this allows us to use filenames rather than animebytes selfmade names for single episodes fixing TheXem compatibility for single episodes.
Because this is a breaking change i made the option opt off by default and user have to enable before anything changes.
* This implements #1115 for Single episodes only thus not closing it completely, for season pack support there needs to be more done or it would just end up hacky on our side again

New: (AnimeBytes) add filename support for single episodes

---

src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornParser.cs

NO
> Try testing the indexer in the settings
indexers are not in settings
- Tests
* Fixes #XXXX

Fix confusing session expired test message

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

NO
Title
- Tests
* Fixes #XXXX

update git templates

---

src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazParser.cs

Fixed: (Avistaz) Handle 429 Request Limit Reached

---

src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs

NO
Pending Notifiarr changes
- Tests
* Fixes #XXXX

New: Notifiarr moved from webhook to API

---

src/NzbDrone.Core/Datastore/Migration/022_orpheus_api.cs
src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleSettings.cs
src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs
src/NzbDrone.Core/Indexers/Definitions/Redacted.cs

NO
Use API key for orpheus auth, tidy up Redacted.
* Fixes #137

Swap Orpheus to API key

---

src/NzbDrone.Core/Notifications/Notifiarr/Notifiarr.cs
src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrProxy.cs
src/NzbDrone.Core/Notifications/Webhook/Webhook.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs
src/NzbDrone.Core/Notifications/Webhook/WebhookPayload.cs

NO
Create Webhook base, convert Notifiarr to JSON payloads, standardize payload from Webhook and Notifiarr to simplify changes to both.

Convert Notifiarr Payload to JSON, Standardize with Webhook

---

src/NzbDrone.Core.Test/Datastore/Migration/022_orpheus_apiFixture.cs
src/NzbDrone.Core.Test/Prowlarr.Core.Test.csproj
src/NzbDrone.Core/Datastore/Migration/008_redacted_api.cs
src/NzbDrone.Core/Datastore/Migration/022_orpheus_api.cs

YES (Fix)
Ensure Orpheus migration runs on postgres, add a test so that migration gets checked on postgres.

Fixed: Orpheus migration fails on Postgres

---

src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs

NO
https://discord.com/channels/264387956343570434/1028840523106107394/1042547671510036600
- Tests
* Fixes #XXXX

Fixed: (SpeedApp) Migrate Legacy URL without slash

---

src/NzbDrone.Host/Startup.cs

(cherry picked from commit 5400bce1295bdc4198d2cfe0b9258bbb7ccf0852)
NO
title
- Tests
* Fixes #1199

Fixed: Publish ApplicationStartingEvent during startup

---

src/NzbDrone.Core/Indexers/HttpIndexerBase.cs

NO
better error handling and improved transparency for backoff logic 
-  Tests
*

Fixed: Indexer Error handling improvements

---

src/NzbDrone.Core.Test/IndexerTests/AvistazTests/AvistazFixture.cs
src/NzbDrone.Core.Test/IndexerTests/AvistazTests/ExoticazFixture.cs
src/NzbDrone.Core.Test/IndexerTests/AvistazTests/PrivateHDFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazApi.cs
src/NzbDrone.Core/Indexers/Definitions/Avistaz/AvistazParser.cs

NO
Pre Fix
Post Fix
* Fixes #1212

Fixed: (Avistaz Family) Age Parsing

---

src/NzbDrone.Core/Indexers/Definitions/Torznab/Torznab.cs

Fixed: (MTV) Torznab Api Path

---

src/NzbDrone.Core/Indexers/Definitions/Nebulance.cs

According to their H&R rules.
NO

Fixed: (Indexer) Changed MinimumSeedTime for NBL

---

src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs

NO
- Currently when filtering by something different than `Audio`, for example `Books`, even if the API returns something it shows 0 rows since the latest aren't eligible as books. This should fix that. 
- Added `Label` and `Year` to search.

Fixed: (Indexer) Changed OPS to use filters for categories, label and year

---

src/NzbDrone.Core/Indexers/Definitions/Torznab/TorznabRssParser.cs

NO
MTV just fixed their API and I haven't seen these in Prowlarr.

Fixed: Changed torznab parser to use additional attributes

---

src/NzbDrone.Core/Indexers/Definitions/FileList/FileList.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListApi.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListParser.cs

 Fixed: (FileList) Changed FL to use internal flag

---

src/NzbDrone.Core/Indexers/Definitions/Libble.cs

NO
Add Libble as C# indexer with 2FA support
Please don't hesitate to do a code review. 🤒

New: (Indexer) Torrent Libble with 2FA support

---

src/NzbDrone.Core.Test/IndexerTests/FileListTests/FileListFixture.cs

Fixed: (Filelist) Use UTC in tests

---

src/NzbDrone.Core/Localization/Core/en.json

NO
Title.
- users do not realize that this is to setup/enable auth
- the refer to FAQ should cut down on External support requests
- 
-  Tests
- [] [Wiki Updates](https://wiki.servarr.com)
* Fixes #XXXX

improve authentication required wording

---

src/NzbDrone.Core/Indexers/Definitions/GreatPosterWall.cs

and map categories accordingly
NO
On Windows `DateTimeOffset().LocalDateTime` seems to be okay, but on Linux it seems to think my localtime it's UTC then adds the difference once again, thus doubling my timezone. So let's try `DateTimeOffset().UtcDateTime`.
Also category mapping by resolution, just like Avistaz does.

Fixed: (GreatPosterWall) Use UTC for PublishDate, order releases

---

src/NzbDrone.Core/Indexers/Definitions/FileList/FileListParser.cs
src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBitsParser.cs
src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornParser.cs
src/NzbDrone.Core/Indexers/Definitions/Torznab/TorznabRssParser.cs
src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs

Fixed: (Torznab) Use HashSet to prevent duplicated flags

---

src/NzbDrone.Core/Indexers/Definitions/MyAnonamouse.cs

NO
- `ExcludeVip` was a little confusing for me, so I replaced it with `SearchType` which contains multiple options to choose from.
- fixed pagination since their API supports it.
- add search in narrator by default, add description and series as settings
- rename title of the setting `Freeleech` to something more descriptive
- show first 5 authors in title, not just the first one
- use description
- removed double slash from links
So far I'm still happy with `DownloadVolumeFactor = item.Free ? 0 : 1`, which should be something like `DownloadVolumeFactor = item.Free ? 0 : item.FreeVip ? 0 : 1` if you're VIP.
I don't know if to use a boolean setting to check `FreeVip` or a date, but since you can buy VIP all the time with bonus points it's a little annoying to always change the date since …

Fixed: (MyAnonamouse) Added search type options, search in narrator/series as settings

---

src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs

NO
- updated categories 
- fixed authentication due to redirect and missing successful login message
- improved the searchUrl build logic by using collection for params and to append the query string only if has values.
* Fixes #1301

Fixed: (ImmortalSeed) Updated categories, improved searchUrl build and fixed auth

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs

NO
Fixes division by zero: ```... for Term: [], Offset: 0, Limit: 0, Categories: []```
* Fixes #1311

Fixed: (IPTorrents) Fix pagination when limit is zero

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: (BeyondHD) Cleanse RSSKey on Grabs

---

src/NzbDrone.Core/Indexers/Definitions/HDSpace.cs

NO
- Some trackers replace non-alphanumeric chars with spaces, thus making the release group unrecognizable by Radarr/Sonarr.
- improvements to rows' selectors.

Fixed: (HD-Space) Use torrent name as release title

---

src/NzbDrone.Core/Indexers/Definitions/HDTorrents.cs

NO
- According to their FAQ 
- Fixed the categories for movies Blu-Ray to match. They have Blu-Ray for TV as well but there's no counterpart in NewznabStandardCategory.
- Added the internal flag

Fixed: (HD-Torrents) Add more alt domains, add Internal flag and fix Blu-Ray categories

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: (AvistaZ/Anthelion) Cleanse pid, api_key and token

---

src/NzbDrone.Core.Test/IndexerTests/FileListTests/FileListFixture.cs
src/NzbDrone.Core.Test/IndexerTests/FileListTests/FileListRequestGeneratorFixture.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileList.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListApi.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListParser.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListRequestGenerator.cs
src/NzbDrone.Core/Indexers/Definitions/FileList/FileListSettings.cs

NO
- Don't send episode without season
- Add description/genres
- Check Content-Type is JSON
- Use `DateTimeStyles.AdjustToUniversal`
- Adjusted the tests

Fixed: (FileList) RequestGenerator refactoring, append slash to IndexerUrl

---

src/NzbDrone.Core.Test/IndexerTests/OrpheusTests/OrpheusFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs

Fixed: (Orpheus) Add remaster title and year to release title

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/SceneTime.cs

Fixed: (IPTorrents/SceneTime) Remove advanced from freeleech only setting

---

src/NzbDrone.Common.Test/InstrumentationTests/CleanseLogMessageFixture.cs
src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs

Fixed: (SpeedApp) Fix cleanse token from response when it's the only field

---

src/NzbDrone.Core/Indexers/Definitions/Shizaproject.cs

NO
See https://github.com/Jackett/Jackett/issues/13762#issuecomment-1341895132

Fixed: (Shizaproject) Obsolete: Site unavailable

---

src/NzbDrone.Core/Indexers/Definitions/GreatPosterWall.cs

NO
Revert change to fix a regression introduced in 57dac6afdde69757a7cd88532844aa61e226b463

Fixed: (GreatPosterWall) Revert category to default to Movies

---

src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs

NO
Follow https://github.com/Jackett/Jackett/commit/578de3ca42ad1b25814bb2b12e2f88fa699154a2
Related: https://github.com/Prowlarr/Indexers/pull/298

Fixed: (Cardigann) Bump to v8

---

src/NzbDrone.Core/Indexers/Definitions/IPTorrents.cs
src/NzbDrone.Core/Indexers/Definitions/Nebulance.cs
src/NzbDrone.Core/Indexers/Definitions/RetroFlix.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedApp/SpeedAppBase.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedCD.cs

NO
A nice improvement cleaning up titles of `REQ|REQUEST|REQUESTED`

Fixed: (assorted) Improve clean titles

---

src/NzbDrone.Core/Indexers/Definitions/ImmortalSeed.cs

NO
- Fixed tvsearch with season & episode
- Added MST and MR.
- Improved parsing a little bit

Fixed: (ImmortalSeed) Improve tv search with season+ep and parsing

---

src/NzbDrone.Core.Test/IndexerTests/OrpheusTests/OrpheusFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs
src/NzbDrone.Core/Indexers/Definitions/Redacted.cs

NO
- Search improvements for RED already done in OPS.
- Add release type to title and match titles between OPS and RED
- Removed label from caps to fix 0 results in some weird cases 
- Fix categories for OPS

Fixed: (Redacted/Orpheus) Search requests and title improvements

---

src/NzbDrone.Core/History/HistoryService.cs
src/NzbDrone.Core/IndexerSearch/Definitions/BookSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/Definitions/MovieSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/Definitions/MusicSearchCriteria.cs
src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/IndexerSearch/Definitions/TvSearchCriteria.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/Cardigann.cs
src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs
src/NzbDrone.Core/Indexers/Definitions/SubsPlease.cs
src/NzbDrone.Core/Indexers/HttpIndexerBase.cs
src/NzbDrone.Core/Indexers/IndexerBase.cs

NO
Fix IsRss to work properly with new query options
Add method to filter search results by query if is not an id search

Filter search criteria

---

src/NzbDrone.Common/Extensions/StringExtensions.cs
src/NzbDrone.Core.Test/ParserTests/DateUtilFixture.cs
src/NzbDrone.Core.Test/ParserTests/ParseUtilFixture.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs
src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs
src/NzbDrone.Core/Parser/DateTimeUtil.cs
src/NzbDrone.Core/Parser/ParseUtil.cs
src/Prowlarr.Benchmark.Test/ParserTests/DateTimeUtilFixture.cs
src/Prowlarr.Benchmark.Test/ParserTests/ParseUtilFixture.cs
src/Prowlarr.Benchmark.Test/Program.cs
src/Prowlarr.Benchmark.Test/Prowlarr.Benchmark.Test.csproj
src/Prowlarr.sln

NO
Basic benchmark tests for parsing methods
2700X improvement in ParseLongFromString
2X improvement in DateUtil Parsing

Benchmark Tests

---

src/NzbDrone.Core/Indexers/Definitions/Xthor/XthorParser.cs

Example of link actually: https://xthor.tkdetails.php/?id=1
NO
* Fixes #XXXX

fix(xthor): update details link

---

src/NzbDrone.Core/Indexers/Definitions/Animedia.cs

Fixed: (Animedia) Description Language

---

azure-pipelines.yml
src/NuGet.config
src/NzbDrone.Core.Test/Datastore/DatabaseFixture.cs
src/NzbDrone.Core/Datastore/Migration/036_postgres_update_timestamp_columns_to_with_timezone.cs
src/NzbDrone.Core/Prowlarr.Core.csproj

(cherry picked from commit d55864f86914199aa0c4ee37df1e42e6ad71ef4f)
YES - 036
* Fixes #1823

Fixed: PostgreSQL timezone issues

---

src/NzbDrone.Core/IndexerSearch/Definitions/SearchCriteriaBase.cs
src/NzbDrone.Core/IndexerSearch/NewznabRequest.cs
src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs
src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRequestGenerator.cs

NO
Adds support for maxage parameter to newznab API. Also adds query support to nab indexers

New: Add support for MaxAge to Newznab API

---

src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornParser.cs
src/NzbDrone.Core/Indexers/Definitions/PassThePopcorn/PassThePopcornRequestGenerator.cs

NO
PTP increasingly strict; return invalid request instead of 429s.
- [] Tests
- [] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [] [Wiki Updates](https://wiki.servarr.com)
* Fixes UX

New: (PTP) Improve Error Handling
